# generated by datamodel-codegen:
#   filename:  rgb-lightning-node.yaml

from __future__ import annotations

from enum import Enum
from typing import Literal

from kaleidoswap_sdk._generated.base import BaseNodeModel
from pydantic import Field


class AddressResponse(BaseNodeModel):
    address: str | None = None


class AssetBalanceRequest(BaseNodeModel):
    asset_id: str | None = None


class AssetBalanceResponse(BaseNodeModel):
    settled: int | None = None
    future: int | None = None
    spendable: int | None = None
    offchain_outbound: int | None = None
    offchain_inbound: int | None = None


class AssetMetadataRequest(BaseNodeModel):
    asset_id: str | None = None


class AssetSchema(Enum):
    nia = "Nia"
    uda = "Uda"
    cfa = "Cfa"


class AssignmentAny(BaseNodeModel):
    type: Literal["Any"]


class AssignmentFungible(BaseNodeModel):
    type: Literal["Fungible"]
    value: int


class AssignmentInflationRight(BaseNodeModel):
    type: Literal["InflationRight"]
    value: int


class AssignmentNonFungible(BaseNodeModel):
    type: Literal["NonFungible"]


class AssignmentReplaceRight(BaseNodeModel):
    type: Literal["ReplaceRight"]


class BackupRequest(BaseNodeModel):
    backup_path: str | None = None
    password: str | None = None


class BitcoinNetwork(Enum):
    mainnet = "Mainnet"
    testnet = "Testnet"
    testnet4 = "Testnet4"
    signet = "Signet"
    regtest = "Regtest"


class BlockTime(BaseNodeModel):
    height: int | None = None
    timestamp: int | None = None


class BtcBalance(BaseNodeModel):
    settled: int | None = None
    future: int | None = None
    spendable: int | None = None


class BtcBalanceRequest(BaseNodeModel):
    skip_sync: bool | None = None


class BtcBalanceResponse(BaseNodeModel):
    vanilla: BtcBalance | None = None
    colored: BtcBalance | None = None


class ChangePasswordRequest(BaseNodeModel):
    old_password: str | None = None
    new_password: str | None = None


class ChannelStatus(Enum):
    opening = "Opening"
    opened = "Opened"
    closing = "Closing"


class CheckIndexerUrlRequest(BaseNodeModel):
    indexer_url: str | None = None


class CheckProxyEndpointRequest(BaseNodeModel):
    proxy_url: str | None = None


class CloseChannelRequest(BaseNodeModel):
    channel_id: str | None = None
    peer_pubkey: str | None = None
    force: bool | None = None


class ConnectPeerRequest(BaseNodeModel):
    peer_pubkey_and_addr: str | None = None


class CreateUtxosRequest(BaseNodeModel):
    up_to: bool | None = None
    num: int | None = None
    size: int | None = None
    fee_rate: float | None = None
    skip_sync: bool | None = None


class DecodeLNInvoiceRequest(BaseNodeModel):
    invoice: str | None = None


class DecodeLNInvoiceResponse(BaseNodeModel):
    amt_msat: int | None = None
    expiry_sec: int | None = None
    timestamp: int | None = None
    asset_id: str | None = None
    asset_amount: int | None = None
    payment_hash: str | None = None
    payment_secret: str | None = None
    payee_pubkey: str | None = None
    network: BitcoinNetwork | None = None


class DecodeRGBInvoiceRequest(BaseNodeModel):
    invoice: str | None = None


class DisconnectPeerRequest(BaseNodeModel):
    peer_pubkey: str | None = None


class EmbeddedMedia(BaseNodeModel):
    mime: str | None = None
    data: list[int] | None = None


class EmptyResponse(BaseNodeModel):
    pass


class EstimateFeeRequest(BaseNodeModel):
    blocks: int | None = None


class EstimateFeeResponse(BaseNodeModel):
    fee_rate: float | None = None


class FailTransfersRequest(BaseNodeModel):
    batch_transfer_idx: int | None = None
    no_asset_only: bool | None = None
    skip_sync: bool | None = None


class FailTransfersResponse(BaseNodeModel):
    transfers_changed: bool | None = None


class GetAssetMediaRequest(BaseNodeModel):
    digest: str | None = None


class GetAssetMediaResponse(BaseNodeModel):
    bytes_hex: str | None = None


class GetChannelIdRequest(BaseNodeModel):
    temporary_channel_id: str | None = None


class GetChannelIdResponse(BaseNodeModel):
    channel_id: str | None = None


class GetPaymentRequest(BaseNodeModel):
    payment_hash: str | None = None


class GetSwapRequest(BaseNodeModel):
    payment_hash: str | None = None
    taker: bool | None = None


class HTLCStatus(Enum):
    pending = "Pending"
    succeeded = "Succeeded"
    failed = "Failed"


class IndexerProtocol(Enum):
    electrum = "Electrum"
    esplora = "Esplora"


class InitRequest(BaseNodeModel):
    password: str | None = None


class InitResponse(BaseNodeModel):
    mnemonic: str | None = None


class InvoiceStatus(Enum):
    pending = "Pending"
    succeeded = "Succeeded"
    failed = "Failed"
    expired = "Expired"


class InvoiceStatusRequest(BaseNodeModel):
    invoice: str | None = None


class InvoiceStatusResponse(BaseNodeModel):
    status: InvoiceStatus | None = None


class IssueAssetCFARequest(BaseNodeModel):
    amounts: list[int] | None = None
    name: str | None = None
    details: str | None = None
    precision: int | None = None
    file_digest: str | None = None


class IssueAssetNIARequest(BaseNodeModel):
    amounts: list[int] | None = None
    ticker: str | None = None
    name: str | None = None
    precision: int | None = None


class IssueAssetUDARequest(BaseNodeModel):
    ticker: str | None = None
    name: str | None = None
    details: str | None = None
    precision: int | None = None
    media_file_digest: str | None = None
    attachments_file_digests: list[str] | None = None


class KeysendRequest(BaseNodeModel):
    dest_pubkey: str | None = None
    amt_msat: int | None = None
    asset_id: str | None = None
    asset_amount: int | None = None


class KeysendResponse(BaseNodeModel):
    payment_hash: str | None = None
    payment_preimage: str | None = None
    status: HTLCStatus | None = None


class ListAssetsRequest(BaseNodeModel):
    filter_asset_schemas: list[AssetSchema] | None = None


class ListTransactionsRequest(BaseNodeModel):
    skip_sync: bool | None = None


class ListTransfersRequest(BaseNodeModel):
    asset_id: str | None = None


class ListUnspentsRequest(BaseNodeModel):
    skip_sync: bool | None = None


class LNInvoiceRequest(BaseNodeModel):
    amt_msat: int | None = None
    expiry_sec: int | None = None
    asset_id: str | None = None
    asset_amount: int | None = None


class LNInvoiceResponse(BaseNodeModel):
    invoice: str | None = None


class MakerExecuteRequest(BaseNodeModel):
    swapstring: str | None = None
    payment_secret: str | None = None
    taker_pubkey: str | None = None


class MakerInitRequest(BaseNodeModel):
    qty_from: int | None = None
    qty_to: int | None = None
    from_asset: str | None = None
    to_asset: str | None = None
    timeout_sec: int | None = None


class MakerInitResponse(BaseNodeModel):
    payment_hash: str | None = None
    payment_secret: str | None = None
    swapstring: str | None = None


class Media(BaseNodeModel):
    file_path: str | None = None
    mime: str | None = None


class NetworkInfoResponse(BaseNodeModel):
    network: BitcoinNetwork | None = None
    height: int | None = None


class NodeInfoResponse(BaseNodeModel):
    pubkey: str | None = None
    num_channels: int | None = None
    num_usable_channels: int | None = None
    local_balance_sat: int | None = None
    eventual_close_fees_sat: int | None = None
    pending_outbound_payments_sat: int | None = None
    num_peers: int | None = None
    account_xpub_vanilla: str | None = None
    account_xpub_colored: str | None = None
    max_media_upload_size_mb: int | None = None
    rgb_htlc_min_msat: int | None = None
    rgb_channel_capacity_min_sat: int | None = None
    channel_capacity_min_sat: int | None = None
    channel_capacity_max_sat: int | None = None
    channel_asset_min_amount: int | None = None
    channel_asset_max_amount: int | None = None
    network_nodes: int | None = None
    network_channels: int | None = None


class OpenChannelRequest(BaseNodeModel):
    peer_pubkey_and_opt_addr: str | None = None
    capacity_sat: int | None = None
    push_msat: int | None = None
    asset_amount: int | None = None
    asset_id: str | None = None
    public: bool | None = None
    with_anchors: bool | None = None
    fee_base_msat: int | None = None
    fee_proportional_millionths: int | None = None
    temporary_channel_id: str | None = None


class OpenChannelResponse(BaseNodeModel):
    temporary_channel_id: str | None = None


class Payment(BaseNodeModel):
    amt_msat: int | None = None
    asset_amount: int | None = None
    asset_id: str | None = None
    payment_hash: str | None = None
    inbound: bool | None = None
    status: HTLCStatus | None = None
    created_at: int | None = None
    updated_at: int | None = None
    payee_pubkey: str | None = None


class Peer(BaseNodeModel):
    pubkey: str | None = None


class PostAssetMediaRequest(BaseNodeModel):
    file: bytes | None = None


class PostAssetMediaResponse(BaseNodeModel):
    digest: str | None = None


class ProofOfReserves(BaseNodeModel):
    utxo: str | None = None
    proof: list[int] | None = None


class RecipientType(Enum):
    blind = "Blind"
    witness = "Witness"


class RefreshRequest(BaseNodeModel):
    skip_sync: bool | None = None


class RestoreRequest(BaseNodeModel):
    backup_path: str | None = None
    password: str | None = None


class RevokeTokenRequest(BaseNodeModel):
    token: str | None = None


class RgbAllocation(BaseNodeModel):
    asset_id: str | None = None
    assignment: AssignmentFungible | None = None
    settled: bool | None = None


class RgbInvoiceResponse(BaseNodeModel):
    recipient_id: str | None = None
    invoice: str | None = None
    expiration_timestamp: int | None = None
    batch_transfer_idx: int | None = None


class SendBtcRequest(BaseNodeModel):
    amount: int | None = None
    address: str | None = None
    fee_rate: float | None = None
    skip_sync: bool | None = None


class SendBtcResponse(BaseNodeModel):
    txid: str | None = None


class SendOnionMessageRequest(BaseNodeModel):
    node_ids: list[str] | None = None
    tlv_type: int | None = None
    data: str | None = None


class SendPaymentRequest(BaseNodeModel):
    invoice: str | None = None


class SendPaymentResponse(BaseNodeModel):
    payment_hash: str | None = None
    payment_secret: str | None = None
    status: HTLCStatus | None = None


class SendRgbResponse(BaseNodeModel):
    txid: str | None = None


class SignMessageRequest(BaseNodeModel):
    message: str | None = None


class SignMessageResponse(BaseNodeModel):
    signed_message: str | None = None


class SwapStatus(Enum):
    waiting = "Waiting"
    pending = "Pending"
    succeeded = "Succeeded"
    expired = "Expired"
    failed = "Failed"


class TakerRequest(BaseNodeModel):
    swapstring: str | None = None


class Token(BaseNodeModel):
    index: int | None = None
    ticker: str | None = None
    name: str | None = None
    details: str | None = None
    embedded_media: EmbeddedMedia | None = None
    media: Media | None = None
    attachments: dict[str, Media] | None = None
    reserves: ProofOfReserves | None = None


class TokenLight(BaseNodeModel):
    index: int | None = None
    ticker: str | None = None
    name: str | None = None
    details: str | None = None
    embedded_media: bool | None = None
    media: Media | None = None
    attachments: dict[str, Media] | None = None
    reserves: bool | None = None


class TransactionType(Enum):
    rgb_send = "RgbSend"
    drain = "Drain"
    create_utxos = "CreateUtxos"
    user = "User"


class TransferKind(Enum):
    issuance = "Issuance"
    receive_blind = "ReceiveBlind"
    receive_witness = "ReceiveWitness"
    send = "Send"
    inflation = "Inflation"


class TransferStatus(Enum):
    waiting_counterparty = "WaitingCounterparty"
    waiting_confirmations = "WaitingConfirmations"
    settled = "Settled"
    failed = "Failed"


class UnlockRequest(BaseNodeModel):
    password: str | None = None
    bitcoind_rpc_username: str | None = None
    bitcoind_rpc_password: str | None = None
    bitcoind_rpc_host: str | None = None
    bitcoind_rpc_port: int | None = None
    indexer_url: str | None = None
    proxy_endpoint: str | None = None
    announce_addresses: list[str] | None = None
    announce_alias: str | None = None


class Utxo(BaseNodeModel):
    outpoint: str | None = None
    btc_amount: int | None = None
    colorable: bool | None = None


class WitnessData(BaseNodeModel):
    amount_sat: float | None = None
    blinding: float | None = None


class AssetCFA(BaseNodeModel):
    asset_id: str | None = None
    name: str | None = None
    details: str | None = None
    precision: int | None = None
    issued_supply: int | None = None
    timestamp: int | None = None
    added_at: int | None = None
    balance: AssetBalanceResponse | None = None
    media: Media | None = None


class AssetMetadataResponse(BaseNodeModel):
    asset_schema: AssetSchema | None = None
    initial_supply: int | None = None
    max_supply: int | None = None
    known_circulating_supply: int | None = None
    timestamp: int | None = None
    name: str | None = None
    precision: int | None = None
    ticker: str | None = None
    details: str | None = None
    token: Token | None = None


class AssetNIA(BaseNodeModel):
    asset_id: str | None = None
    ticker: str | None = None
    name: str | None = None
    details: str | None = None
    precision: int | None = None
    issued_supply: int | None = None
    timestamp: int | None = None
    added_at: int | None = None
    balance: AssetBalanceResponse | None = None
    media: Media | None = None


class AssetUDA(BaseNodeModel):
    asset_id: str | None = None
    ticker: str | None = None
    name: str | None = None
    details: str | None = None
    precision: int | None = None
    timestamp: int | None = None
    added_at: int | None = None
    balance: AssetBalanceResponse | None = None
    token: TokenLight | None = None


class Channel(BaseNodeModel):
    channel_id: str | None = None
    funding_txid: str | None = None
    peer_pubkey: str | None = None
    peer_alias: str | None = None
    short_channel_id: int | None = None
    status: ChannelStatus | None = None
    ready: bool | None = None
    capacity_sat: int | None = None
    local_balance_sat: int | None = None
    outbound_balance_msat: int | None = None
    inbound_balance_msat: int | None = None
    next_outbound_htlc_limit_msat: int | None = None
    next_outbound_htlc_minimum_msat: int | None = None
    is_usable: bool | None = None
    public: bool | None = None
    asset_id: str | None = None
    asset_local_amount: int | None = None
    asset_remote_amount: int | None = None


class CheckIndexerUrlResponse(BaseNodeModel):
    indexer_protocol: IndexerProtocol | None = None


class DecodeRGBInvoiceResponse(BaseNodeModel):
    recipient_id: str | None = None
    recipient_type: RecipientType | None = None
    asset_schema: AssetSchema | None = None
    asset_id: str | None = None
    assignment: (
        AssignmentFungible
        | AssignmentNonFungible
        | AssignmentInflationRight
        | AssignmentReplaceRight
        | AssignmentAny
        | None
    ) = Field(None, discriminator="type")
    network: BitcoinNetwork | None = None
    expiration_timestamp: int | None = None
    transport_endpoints: list[str] | None = None


class GetPaymentResponse(BaseNodeModel):
    payment: Payment | None = None


class IssueAssetCFAResponse(BaseNodeModel):
    asset: AssetCFA | None = None


class IssueAssetNIAResponse(BaseNodeModel):
    asset: AssetNIA | None = None


class IssueAssetUDAResponse(BaseNodeModel):
    asset: AssetUDA | None = None


class ListAssetsResponse(BaseNodeModel):
    nia: list[AssetNIA] | None = None
    uda: list[AssetUDA] | None = None
    cfa: list[AssetCFA] | None = None


class ListChannelsResponse(BaseNodeModel):
    channels: list[Channel] | None = None


class ListPaymentsResponse(BaseNodeModel):
    payments: list[Payment] | None = None


class ListPeersResponse(BaseNodeModel):
    peers: list[Peer] | None = None


class Recipient(BaseNodeModel):
    recipient_id: str | None = None
    witness_data: WitnessData | None = None
    assignment: (
        AssignmentFungible
        | AssignmentNonFungible
        | AssignmentInflationRight
        | AssignmentReplaceRight
        | AssignmentAny
        | None
    ) = Field(None, discriminator="type")
    transport_endpoints: list[str] | None = None


class RgbInvoiceRequest(BaseNodeModel):
    min_confirmations: int | None = None
    asset_id: str | None = None
    assignment: (
        AssignmentFungible
        | AssignmentNonFungible
        | AssignmentInflationRight
        | AssignmentReplaceRight
        | AssignmentAny
        | None
    ) = Field(None, discriminator="type")
    duration_seconds: int | None = None
    witness: bool | None = None


class SendRgbRequest(BaseNodeModel):
    donation: bool | None = None
    fee_rate: float | None = None
    min_confirmations: int | None = None
    recipient_map: dict[str, list[Recipient]] | None = None
    skip_sync: bool | None = None


class Swap(BaseNodeModel):
    qty_from: int | None = None
    qty_to: int | None = None
    from_asset: str | None = None
    to_asset: str | None = None
    payment_hash: str | None = None
    status: SwapStatus | None = None
    requested_at: int | None = None
    initiated_at: int | None = None
    expires_at: int | None = None
    completed_at: int | None = None


class Transaction(BaseNodeModel):
    transaction_type: TransactionType | None = None
    txid: str | None = None
    received: int | None = None
    sent: int | None = None
    fee: int | None = None
    confirmation_time: BlockTime | None = None


class TransferTransportEndpoint(BaseNodeModel):
    endpoint: str | None = None
    transport_type: Literal["JsonRpc"] | None = None
    used: bool | None = None


class Unspent(BaseNodeModel):
    utxo: Utxo | None = None
    rgb_allocations: list[RgbAllocation] | None = None


class GetSwapResponse(BaseNodeModel):
    swap: Swap | None = None


class ListSwapsResponse(BaseNodeModel):
    maker: list[Swap] | None = None
    taker: list[Swap] | None = None


class ListTransactionsResponse(BaseNodeModel):
    transactions: list[Transaction] | None = None


class ListUnspentsResponse(BaseNodeModel):
    unspents: list[Unspent] | None = None


class Transfer(BaseNodeModel):
    idx: int | None = None
    created_at: int | None = None
    updated_at: int | None = None
    status: TransferStatus | None = None
    requested_assignment: AssignmentFungible | None = None
    assignments: list[AssignmentFungible] | None = None
    kind: TransferKind | None = None
    txid: str | None = None
    recipient_id: str | None = None
    receive_utxo: str | None = None
    change_utxo: str | None = None
    expiration: int | None = None
    transport_endpoints: list[TransferTransportEndpoint] | None = None


class ListTransfersResponse(BaseNodeModel):
    transfers: list[Transfer] | None = None
