//! Auto-generated models from OpenAPI specification.
//!
//! DO NOT EDIT - This file is generated by scripts/generate_models.py

use serde::{Deserialize, Serialize};

/// Extended asset definition for the trading system.
///
/// Extends AssetDefinition with:
/// - Trading status (is_active)
/// - RGB-specific fields for node API compatibility
/// - Methods to convert to TradableAsset for specific settlements
///
/// NOTE: No balance information here. Balances are tracked per-settlement
/// in wallets/registries, not on the asset itself.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Asset {
    /// Unique identifier (e.g., 'BTC', 'rgb:...')
    pub asset_id: String,
    /// Display ticker (e.g., 'BTC', 'USDT')
    pub ticker: String,
    /// Full name
    pub name: String,
    /// Decimal places (e.g., 8 for BTC, 6 for USDT)
    pub precision: i64,
    #[serde(default)]
    /// Description
    pub details: Option<String>,
    #[serde(default)]
    /// Logo/media
    pub media: Option<Media>,
    #[serde(default)]
    /// Total issued supply
    pub issued_supply: Option<i64>,
    #[serde(default)]
    /// Creation timestamp
    pub timestamp: Option<i64>,
    #[serde(default)]
    /// Active for trading
    pub is_active: Option<bool>,
    #[serde(default)]
    /// RGB interface type
    pub asset_iface: Option<Assetiface>,
    #[serde(default)]
    /// When added to wallet
    pub added_at: Option<i64>,
    #[serde(default)]
    /// Networks where this asset can run
    pub supported_networks: Option<Vec<Networklayer>>,
    #[serde(default)]
    /// Default network for this asset
    pub default_network: Option<Networklayer>,
    /// Get the default protocol for this asset.
    pub default_protocol: Assetprotocol,
}

/// Status of asset delivery via keysend after channel opening
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum Assetdeliverystatus {
    #[serde(rename = "NOT_REQUIRED")]
    NotRequired,
    #[serde(rename = "PENDING")]
    Pending,
    #[serde(rename = "IN_PROGRESS")]
    InProgress,
    #[serde(rename = "COMPLETED")]
    Completed,
    #[serde(rename = "FAILED")]
    Failed,
    #[serde(rename = "RATE_CHANGED")]
    RateChanged,
}

/// AssetIface enum.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum Assetiface {
    #[serde(rename = "RGB20")]
    Rgb20,
    #[serde(rename = "RGB21")]
    Rgb21,
    #[serde(rename = "RGB25")]
    Rgb25,
}

/// Asset protocols that define how assets are issued and transferred.
///
/// These protocols enable the creation and transfer of various assets
/// on top of Bitcoin and its layers.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum Assetprotocol {
    #[serde(rename = "NATIVE_BTC")]
    NativeBtc,
    #[serde(rename = "RGB")]
    Rgb,
    #[serde(rename = "TAPROOT_ASSETS")]
    TaprootAssets,
    #[serde(rename = "LIQUID_ASSET")]
    LiquidAsset,
    #[serde(rename = "SPARK_ASSET")]
    SparkAsset,
    #[serde(rename = "ARKADE_ASSET")]
    ArkadeAsset,
}

/// AssetsOptions model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Assetsoptions {
    #[serde(default)]
    pub name: Option<String>,
    #[serde(default)]
    pub asset_id: Option<String>,
    #[serde(default)]
    pub ticker: Option<String>,
    #[serde(default)]
    pub precision: Option<i64>,
    #[serde(default)]
    pub issued_supply: Option<i64>,
    #[serde(default)]
    pub min_initial_client_amount: Option<i64>,
    #[serde(default)]
    pub max_initial_client_amount: Option<i64>,
    #[serde(default)]
    pub min_initial_lsp_amount: Option<i64>,
    #[serde(default)]
    pub max_initial_lsp_amount: Option<i64>,
    #[serde(default)]
    pub min_channel_amount: Option<i64>,
    #[serde(default)]
    pub max_channel_amount: Option<i64>,
}

/// Response model for asset listing endpoints.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Assetsresponse {
    pub assets: Vec<Asset>,
    #[serde(default)]
    pub network: Option<String>,
    #[serde(default)]
    pub timestamp: Option<i64>,
}

/// BitcoinNetwork enum.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum Bitcoinnetwork {
    Mainnet,
    Testnet,
    Signet,
    Regtest,
}

/// ChannelDetails model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Channeldetails {
    #[serde(default)]
    pub channel_id: Option<String>,
    #[serde(default)]
    pub temporary_channel_id: Option<String>,
    #[serde(default)]
    pub funded_at: Option<String>,
    #[serde(default)]
    pub funding_outpoint: Option<String>,
    #[serde(default)]
    pub expires_at: Option<String>,
}

/// ChannelFees model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Channelfees {
    pub setup_fee: i64,
    pub capacity_fee: i64,
    pub duration_fee: i64,
    pub total_fee: i64,
    #[serde(default)]
    pub applied_discount: Option<f64>,
    #[serde(default)]
    pub discount_code: Option<String>,
}

/// ConfirmSwapRequest model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Confirmswaprequest {
    pub swapstring: String,
    pub taker_pubkey: String,
    pub payment_hash: String,
}

/// ConfirmSwapResponse model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Confirmswapresponse {
    pub status: i64,
    pub message: String,
}

/// CreateOrderRequest model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Createorderrequest {
    pub client_pubkey: String,
    pub lsp_balance_sat: i64,
    pub client_balance_sat: i64,
    pub required_channel_confirmations: i64,
    pub funding_confirms_within_blocks: i64,
    pub channel_expiry_blocks: i64,
    #[serde(default)]
    pub token: Option<String>,
    #[serde(default)]
    pub refund_onchain_address: Option<String>,
    #[serde(default)]
    pub announce_channel: Option<bool>,
    #[serde(default)]
    pub asset_id: Option<String>,
    #[serde(default)]
    pub lsp_asset_amount: Option<i64>,
    #[serde(default)]
    pub client_asset_amount: Option<i64>,
    #[serde(default)]
    pub rfq_id: Option<String>,
    #[serde(default)]
    /// Optional email for notifications
    pub email: Option<String>,
}

/// CreateSwapOrderRequest model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Createswaporderrequest {
    /// RFQ ID cannot be empty
    pub rfq_id: String,
    /// Complete input specification: asset, ticker, network, protocol, and amount
    pub from_asset: Swapleg,
    /// Complete output specification: asset, ticker, network, protocol, and amount
    pub to_asset: Swapleg,
    /// Destination address/invoice for receiving the to_asset payout
    pub receiver_address: Receiveraddress,
    #[serde(default)]
    pub min_onchain_conf: Option<i64>,
    #[serde(default)]
    pub refund_address: Option<String>,
    #[serde(default)]
    /// Optional email for notifications
    pub email: Option<String>,
}

/// CreateSwapOrderResponse model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Createswaporderresponse {
    pub id: String,
    pub rfq_id: String,
    #[serde(default)]
    pub deposit_address: Option<Receiveraddress>,
    pub status: Swaporderstatus,
}

/// Fee model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Fee {
    pub base_fee: i64,
    pub variable_fee: i64,
    pub fee_rate: f64,
    pub final_fee: i64,
    pub fee_asset: String,
    pub fee_asset_precision: i64,
}

/// GetInfoResponseModel model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Getinforesponsemodel {
    pub lsp_connection_url: String,
    pub options: Orderoptions,
    pub assets: Vec<Assetsoptions>,
}

/// GetOrderRequest model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Getorderrequest {
    pub order_id: String,
}

/// Request model for retrieving a trading pair.
///
/// Supports multiple identification methods:
/// 1. By pair_id (UUID)
/// 2. By asset IDs (from_asset_id and quote_asset_id)
/// 3. By tickers (pair_ticker like "USDT/XAUT" or base_ticker and quote_ticker)
///
/// Exactly one identification method must be provided.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Getpairrequest {
    #[serde(default)]
    /// Pair ID (UUID) to identify the pair
    pub pair_id: Option<String>,
    #[serde(default)]
    /// Base asset ID (use with quote_asset_id)
    pub from_asset_id: Option<String>,
    #[serde(default)]
    /// Quote asset ID (use with from_asset_id)
    pub quote_asset_id: Option<String>,
    #[serde(default)]
    /// Pair ticker in format 'BASE/QUOTE' (e.g., 'USDT/XAUT')
    pub pair_ticker: Option<String>,
    #[serde(default)]
    /// Base asset ticker (use with quote_ticker)
    pub base_ticker: Option<String>,
    #[serde(default)]
    /// Quote asset ticker (use with base_ticker)
    pub quote_ticker: Option<String>,
}

/// Media model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Media {
    pub file_path: String,
    pub digest: String,
    pub mime: String,
}

/// NetworkInfoResponse model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Networkinforesponse {
    pub network: Bitcoinnetwork,
    pub height: i64,
}

/// Network layers where assets can exist and be transacted.
///
/// These represent the different settlement and transaction layers
/// in the Bitcoin ecosystem.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum Networklayer {
    #[serde(rename = "BTC_ONCHAIN")]
    BtcOnchain,
    #[serde(rename = "LIGHTNING")]
    Lightning,
    #[serde(rename = "CASHU")]
    Cashu,
    #[serde(rename = "LIQUID")]
    Liquid,
    #[serde(rename = "SPARK")]
    Spark,
    #[serde(rename = "ARKADE")]
    Arkade,
}

/// NodeInfoResponse model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Nodeinforesponse {
    #[serde(default)]
    pub pubkey: Option<String>,
    #[serde(default)]
    pub network: Option<String>,
    #[serde(default)]
    pub block_height: Option<i64>,
}

/// OrderHistoryRequest model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Orderhistoryrequest {
    #[serde(default)]
    /// Filter by order status. If not provided, returns filled orders
    pub status: Option<Swaporderstatus>,
    #[serde(default)]
    /// Maximum number of orders to return
    pub limit: Option<i64>,
    #[serde(default)]
    /// Number of orders to skip for pagination
    pub skip: Option<i64>,
}

/// OrderHistoryResponse model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Orderhistoryresponse {
    /// List of orders
    pub data: Vec<Orderhistorysummary>,
    pub pagination: Paginationmeta,
}

/// Simplified order information for history listing
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Orderhistorysummary {
    /// Order ID
    pub id: String,
    /// Order status
    pub status: Swaporderstatus,
    /// Asset being swapped from
    pub from_asset: String,
    /// Amount of from_asset
    pub from_amount: i64,
    /// Asset being swapped to
    pub to_asset: String,
    /// Amount of to_asset
    pub to_amount: i64,
    /// Order creation timestamp
    pub created_at: i64,
    #[serde(default)]
    /// Order completion timestamp
    pub filled_at: Option<i64>,
}

/// OrderOptions model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Orderoptions {
    #[serde(default)]
    pub min_required_channel_confirmations: Option<i64>,
    #[serde(default)]
    pub min_funding_confirms_within_blocks: Option<i64>,
    #[serde(default)]
    pub min_onchain_payment_confirmations: Option<i64>,
    #[serde(default)]
    pub supports_zero_channel_reserve: Option<bool>,
    #[serde(default)]
    pub min_onchain_payment_size_sat: Option<i64>,
    #[serde(default)]
    pub max_channel_expiry_blocks: Option<i64>,
    #[serde(default)]
    pub min_initial_client_balance_sat: Option<i64>,
    #[serde(default)]
    pub max_initial_client_balance_sat: Option<i64>,
    #[serde(default)]
    pub min_initial_lsp_balance_sat: Option<i64>,
    #[serde(default)]
    pub max_initial_lsp_balance_sat: Option<i64>,
    #[serde(default)]
    pub min_channel_balance_sat: Option<i64>,
    #[serde(default)]
    pub max_channel_balance_sat: Option<i64>,
}

/// OrderResponse model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Orderresponse {
    pub order_id: String,
    pub client_pubkey: String,
    pub lsp_balance_sat: i64,
    pub client_balance_sat: i64,
    pub required_channel_confirmations: i64,
    pub funding_confirms_within_blocks: i64,
    pub channel_expiry_blocks: i64,
    #[serde(default)]
    pub token: Option<String>,
    #[serde(default)]
    pub created_at: Option<String>,
    pub announce_channel: bool,
    pub order_state: Orderstate,
    pub payment: Paymentdetails,
    #[serde(default)]
    pub channel: Option<Channeldetails>,
    #[serde(default)]
    pub asset_id: Option<String>,
    #[serde(default)]
    pub lsp_asset_amount: Option<i64>,
    #[serde(default)]
    pub client_asset_amount: Option<i64>,
    #[serde(default)]
    pub rfq_id: Option<String>,
    #[serde(default)]
    pub asset_price_sat: Option<i64>,
    #[serde(default)]
    pub asset_delivery_status: Option<Assetdeliverystatus>,
    #[serde(default)]
    pub asset_delivery_payment_hash: Option<String>,
    #[serde(default)]
    pub asset_delivery_completed_at: Option<String>,
    #[serde(default)]
    pub asset_delivery_error: Option<String>,
    #[serde(default)]
    pub failure_reason: Option<String>,
}

/// OrderState enum.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum Orderstate {
    #[serde(rename = "CREATED")]
    Created,
    #[serde(rename = "CHANNEL_OPENING")]
    ChannelOpening,
    #[serde(rename = "COMPLETED")]
    Completed,
    #[serde(rename = "FAILED")]
    Failed,
    #[serde(rename = "PENDING_RATE_DECISION")]
    PendingRateDecision,
}

/// OrderStatsResponse model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Orderstatsresponse {
    /// Count of orders by status
    pub status_counts: std::collections::HashMap<String, i64>,
    /// Total volume of filled orders
    pub filled_orders_volume: i64,
    /// Total count of filled orders
    pub filled_orders_count: i64,
}

/// Pagination metadata
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Paginationmeta {
    /// Total number of items matching the filter
    pub total: i64,
    /// Number of items per page
    pub limit: i64,
    /// Number of items skipped
    pub skip: i64,
    /// Current page number (1-indexed)
    pub current_page: i64,
    /// Total number of pages
    pub total_pages: i64,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_previous: bool,
}

/// Request for a quote on a trading pair using SwapLegInput.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Pairquoterequest {
    /// Source leg specification (asset_id, network, protocol, amount)
    pub from_asset: Swapleginput,
    /// Destination leg specification (asset_id, network, protocol, amount)
    pub to_asset: Swapleginput,
}

/// Response containing a quote for a trading pair.
///
/// Uses full SwapLeg for both sides, providing complete asset details
/// including ticker, name, precision, network, protocol, and amount.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Pairquoteresponse {
    pub rfq_id: String,
    /// Complete source leg specification with amount and details
    pub from_asset: Swapleg,
    /// Complete destination leg specification with amount and details
    pub to_asset: Swapleg,
    /// Price of 1 whole unit of from_asset (e.g., 1 BTC) in terms of the smallest unit of to_asset (e.g., USDT with precision 6). Matches PriceData.price for the given rfq_id.
    pub price: i64,
    pub fee: Fee,
    /// Quote creation timestamp (seconds since epoch)
    pub timestamp: i64,
    /// Quote expiry timestamp (seconds since epoch)
    pub expires_at: i64,
    #[serde(default)]
    /// True if this is a submarine swap (same asset, different networks)
    pub is_submarine_swap: Option<bool>,
}

/// PaymentBolt11 model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Paymentbolt11 {
    pub state: Paymentstate,
    pub expires_at: String,
    pub fee_total_sat: i64,
    pub order_total_sat: i64,
    pub invoice: String,
}

/// PaymentDetails model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Paymentdetails {
    pub bolt11: Paymentbolt11,
    pub onchain: Paymentonchain,
}

/// PaymentOnchain model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Paymentonchain {
    pub state: Paymentstate,
    pub expires_at: String,
    pub fee_total_sat: i64,
    pub order_total_sat: i64,
    pub address: String,
    pub min_fee_for_0conf: i64,
    pub min_onchain_payment_confirmations: i64,
    #[serde(default)]
    pub refund_onchain_address: Option<String>,
    #[serde(default)]
    pub payment_status: Option<String>,
    #[serde(default)]
    /// Payment difference in satoshis. Positive for overpayment, negative for underpayment, zero for exact payment
    pub payment_difference: Option<i64>,
    #[serde(default)]
    pub last_payment_check: Option<i64>,
}

/// PaymentState enum.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum Paymentstate {
    #[serde(rename = "EXPECT_PAYMENT")]
    ExpectPayment,
    #[serde(rename = "HOLD")]
    Hold,
    #[serde(rename = "PAID")]
    Paid,
    #[serde(rename = "REFUNDED")]
    Refunded,
    #[serde(rename = "TO_REFUND")]
    ToRefund,
}

/// Payment status for onchain payments with support for partial payments.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum Paymentstatus {
    #[serde(rename = "NOT_PAID")]
    NotPaid,
    #[serde(rename = "UNDERPAID")]
    Underpaid,
    #[serde(rename = "PAID")]
    Paid,
    #[serde(rename = "OVERPAID")]
    Overpaid,
}

/// Request for user to accept new rate or request refund
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Ratedecisionrequest {
    pub order_id: String,
    pub accept_new_rate: bool,
}

/// Response after user makes rate decision
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Ratedecisionresponse {
    pub order_id: String,
    pub decision_accepted: bool,
    pub message: String,
    #[serde(default)]
    pub refund_txid: Option<String>,
}

/// Receiver address or invoice with its format.
///
/// Encapsulates the destination for receiving funds along with
/// metadata about what format it uses.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Receiveraddress {
    /// The actual address, invoice, or token string
    pub address: String,
    /// Format of the receiver address
    pub format: Receiveraddressformat,
}

/// Supported receiver address and invoice formats.
///
/// Different networks and protocols use different address/invoice formats
/// for receiving payments.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum Receiveraddressformat {
    #[serde(rename = "BTC_ADDRESS")]
    BtcAddress,
    #[serde(rename = "BOLT11")]
    Bolt11,
    #[serde(rename = "BOLT12")]
    Bolt12,
    #[serde(rename = "LN_ADDRESS")]
    LnAddress,
    #[serde(rename = "RGB_INVOICE")]
    RgbInvoice,
    #[serde(rename = "LIQUID_ADDRESS")]
    LiquidAddress,
    #[serde(rename = "LIQUID_INVOICE")]
    LiquidInvoice,
    #[serde(rename = "SPARK_ADDRESS")]
    SparkAddress,
    #[serde(rename = "SPARK_INVOICE")]
    SparkInvoice,
    #[serde(rename = "ARKADE_ADDRESS")]
    ArkadeAddress,
    #[serde(rename = "ARKADE_INVOICE")]
    ArkadeInvoice,
    #[serde(rename = "CASHU_TOKEN")]
    CashuToken,
}

/// Request model for /retry_delivery endpoint to trigger immediate keysend retry
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Retrydeliveryrequest {
    /// Order ID to retry asset delivery for
    pub order_id: String,
}

/// Response model for /retry_delivery endpoint
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Retrydeliveryresponse {
    /// Status of the request
    pub status: Retrydeliverystatus,
    /// Human-readable message about the result
    pub message: String,
}

/// Status codes for /retry_delivery endpoint responses
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum Retrydeliverystatus {
    #[serde(rename = "processing")]
    Processing,
    #[serde(rename = "not_found")]
    NotFound,
    #[serde(rename = "no_pending_delivery")]
    NoPendingDelivery,
    #[serde(rename = "error")]
    Error,
}

/// Where/how an asset is settled: (network, protocol) combination.
///
/// This is the fundamental context for how an asset is transacted.
/// Examples:
/// - (LIGHTNING, NATIVE_BTC) - BTC on Lightning
/// - (LIGHTNING, RGB) - RGB asset on Lightning
/// - (BTC_ONCHAIN, RGB) - RGB asset on Layer 1
/// - (SPARK, NATIVE_BTC) - BTC on Spark protocol
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Settlementlayer {
    /// Network layer (Lightning, Onchain, Spark, etc.)
    pub network: Networklayer,
    /// Asset protocol (Native BTC, RGB, Taproot Assets, etc.)
    pub protocol: Assetprotocol,
}

/// Swap model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Swap {
    pub qty_from: i64,
    pub qty_to: i64,
    #[serde(default)]
    pub from_asset: Option<String>,
    #[serde(default)]
    pub to_asset: Option<String>,
    pub payment_hash: String,
    pub status: Swapstatus,
    pub requested_at: i64,
    #[serde(default)]
    pub initiated_at: Option<i64>,
    pub expires_at: i64,
    #[serde(default)]
    pub completed_at: Option<i64>,
}

/// Swap Leg: Complete asset specification for one side of a swap.
///
/// Represents a specific asset on a specific settlement layer with an amount.
/// This is the fundamental unit for swap orders - each side (leg) of a swap
/// specifies an asset on a particular network with a specific amount.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Swapleg {
    /// Unique identifier for the asset (e.g., 'BTC', RGB contract ID, etc.)
    pub asset_id: String,
    /// Full name of the asset
    pub name: String,
    /// Asset ticker symbol for display (e.g., 'BTC', 'USDT', 'EURX')
    pub ticker: String,
    /// Network layer where the asset will be transacted
    pub network: Networklayer,
    /// Protocol used for this asset
    pub protocol: Assetprotocol,
    /// Amount of the asset in smallest unit. Must be greater than or equal to zero.
    pub amount: i64,
    /// Number of decimal places for this asset (e.g., 8 for BTC, 6 or 8 for stablecoins)
    pub precision: i64,
}

/// Lightweight input model for specifying one leg of a swap request.
///
/// Only contains the fields the client needs to provide. The service will
/// look up additional details (name, ticker, precision) from the asset registry.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Swapleginput {
    /// Asset identifier (e.g., 'BTC', RGB contract ID)
    pub asset_id: String,
    /// Network layer for this asset
    pub network: Networklayer,
    /// Protocol for this asset
    pub protocol: Assetprotocol,
    #[serde(default)]
    /// Amount in smallest unit (optional - one side must have amount)
    pub amount: Option<i64>,
}

/// SwapOrder model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Swaporder {
    /// Order identifier
    pub id: String,
    /// Quote identifier used to create the order
    pub rfq_id: String,
    #[serde(default)]
    /// Maker node public key
    pub maker_pubkey: Option<String>,
    /// Complete specification for input: asset, ticker, network, protocol, and amount
    pub from_asset: Swapleg,
    /// Complete specification for output: asset, ticker, network, protocol, and amount
    pub to_asset: Swapleg,
    pub price: i64,
    #[serde(default)]
    /// Address/Invoice for the user to deposit funds into
    pub deposit_address: Option<Receiveraddress>,
    #[serde(default)]
    /// Destination address/invoice for receiving the to_asset payout
    pub payout_address: Option<Receiveraddress>,
    #[serde(default)]
    /// Onchain refund address if provided
    pub refund_address: Option<String>,
    #[serde(default)]
    /// Current order status
    pub status: Option<Box<Swaporderstatus>>,
    #[serde(default)]
    /// Creation timestamp (seconds since epoch)
    pub created_at: Option<i64>,
    #[serde(default)]
    /// Expiry timestamp (seconds since epoch)
    pub expires_at: Option<i64>,
    #[serde(default)]
    /// Timestamp when the order was filled
    pub filled_at: Option<i64>,
    #[serde(default)]
    /// Transaction ID of any refund sent
    pub refund_txid: Option<String>,
    #[serde(default)]
    /// Whether the order requires manual refund handling
    pub requires_manual_refund: Option<bool>,
    #[serde(default)]
    /// Status of onchain payment verification
    pub payment_status: Option<Paymentstatus>,
    #[serde(default)]
    /// Payment difference in satoshis (positive for overpayment, negative for underpayment)
    pub payment_difference: Option<i64>,
    #[serde(default)]
    /// Timestamp of the last payment verification
    pub last_payment_check: Option<i64>,
    #[serde(default)]
    /// Notification email address
    pub email: Option<String>,
    #[serde(default)]
    /// Reason the order failed, if applicable
    pub failure_reason: Option<String>,
    /// Fee information from the quote
    pub fee: Fee,
}

/// Request for user to accept new rate or request refund for a swap order
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Swaporderratedecisionrequest {
    /// Swap order ID
    pub order_id: String,
    /// True to accept new rate, False to request refund
    pub accept_new_rate: bool,
}

/// Response after user makes rate decision for a swap order
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Swaporderratedecisionresponse {
    pub order_id: String,
    pub decision_accepted: bool,
    pub message: String,
    #[serde(default)]
    /// Present if refund was requested and processed
    pub refund_txid: Option<String>,
}

/// SwapOrderStatus enum.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum Swaporderstatus {
    #[serde(rename = "OPEN")]
    Open,
    #[serde(rename = "PENDING_PAYMENT")]
    PendingPayment,
    #[serde(rename = "PAID")]
    Paid,
    #[serde(rename = "EXECUTING")]
    Executing,
    #[serde(rename = "FILLED")]
    Filled,
    #[serde(rename = "CANCELLED")]
    Cancelled,
    #[serde(rename = "EXPIRED")]
    Expired,
    #[serde(rename = "FAILED")]
    Failed,
    #[serde(rename = "PENDING_RATE_DECISION")]
    PendingRateDecision,
}

/// SwapOrderStatusRequest model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Swaporderstatusrequest {
    pub order_id: String,
}

/// SwapOrderStatusResponse model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Swaporderstatusresponse {
    pub order_id: String,
    pub status: Swaporderstatus,
    pub order: Swaporder,
}

/// SwapRequest model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Swaprequest {
    pub rfq_id: String,
    pub from_asset: String,
    pub from_amount: i64,
    pub to_asset: String,
    pub to_amount: i64,
}

/// SwapResponse model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Swapresponse {
    pub swapstring: String,
    pub payment_hash: String,
}

/// SwapRoute model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Swaproute {
}

/// SwapStatus enum.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum Swapstatus {
    Waiting,
    Pending,
    Succeeded,
    Expired,
    Failed,
}

/// SwapStatusRequest model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Swapstatusrequest {
    pub payment_hash: String,
}

/// SwapStatusResponse model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Swapstatusresponse {
    #[serde(default)]
    pub swap: Option<Swap>,
}

/// Asset with settlement context(s) for trading operations.
///
/// This unified model supports both:
/// - Single-settlement use cases (swap execution): use network/protocol properties
/// - Multi-settlement use cases (trading pairs): use endpoints list
///
/// When endpoints is provided, network/protocol are derived from the first endpoint.
/// When network/protocol are provided directly, a single endpoint is created.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Tradableasset {
    /// Unique identifier (e.g., 'BTC', 'rgb:...')
    pub asset_id: String,
    /// Display ticker (e.g., 'BTC', 'USDT')
    pub ticker: String,
    /// Full name
    pub name: String,
    /// Decimal places (e.g., 8 for BTC, 6 for USDT)
    pub precision: i64,
    #[serde(default)]
    /// Description
    pub details: Option<String>,
    #[serde(default)]
    /// Logo/media
    pub media: Option<Media>,
    #[serde(default)]
    /// Total issued supply
    pub issued_supply: Option<i64>,
    #[serde(default)]
    /// Creation timestamp
    pub timestamp: Option<i64>,
    #[serde(default)]
    /// Settlement endpoints with trading limits
    pub endpoints: Option<Vec<Tradinglimits>>,
}

/// TradingLimits model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Tradinglimits {
}

/// Complete trading pair with full asset details, routes, and price.
///
/// This is the unified model used for both:
/// - API responses (Pairs API)
/// - Database storage (replaces legacy Pair model)
///
/// Contains all pre-computed information needed to display and validate swaps.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Tradingpair {
    #[serde(default)]
    pub id: Option<String>,
    pub base: Tradableasset,
    pub quote: Tradableasset,
    #[serde(default)]
    pub price: Option<String>,
    #[serde(default)]
    pub routes: Option<Vec<Swaproute>>,
    #[serde(default)]
    pub is_active: Option<bool>,
}

/// Response containing list of trading pairs.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Tradingpairsresponse {
    pub pairs: Vec<Tradingpair>,
    pub total: i64,
    pub timestamp: i64,
}
