//! Auto-generated models from OpenAPI specification.
//!
//! DO NOT EDIT - This file is generated by scripts/generate_models.py

use serde::{Deserialize, Serialize};

/// Type alias for Assignment - maps to dynamic JSON value as it's a union type
pub type Assignment = serde_json::Value;

/// AddressResponse model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Addressresponse {
    #[serde(default)]
    pub address: Option<String>,
}

/// AssetBalanceRequest model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Assetbalancerequest {
    #[serde(default)]
    pub asset_id: Option<String>,
}

/// AssetBalanceResponse model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Assetbalanceresponse {
    #[serde(default)]
    pub settled: Option<i64>,
    #[serde(default)]
    pub future: Option<i64>,
    #[serde(default)]
    pub spendable: Option<i64>,
    #[serde(default)]
    pub offchain_outbound: Option<i64>,
    #[serde(default)]
    pub offchain_inbound: Option<i64>,
}

/// AssetCFA model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Assetcfa {
    #[serde(default)]
    pub asset_id: Option<String>,
    #[serde(default)]
    pub name: Option<String>,
    #[serde(default)]
    pub details: Option<String>,
    #[serde(default)]
    pub precision: Option<i64>,
    #[serde(default)]
    pub issued_supply: Option<i64>,
    #[serde(default)]
    pub timestamp: Option<i64>,
    #[serde(default)]
    pub added_at: Option<i64>,
    #[serde(default)]
    pub balance: Option<Box<Assetbalanceresponse>>,
    #[serde(default)]
    pub media: Option<Box<Media>>,
}

/// AssetMetadataRequest model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Assetmetadatarequest {
    #[serde(default)]
    pub asset_id: Option<String>,
}

/// AssetMetadataResponse model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Assetmetadataresponse {
    #[serde(default)]
    pub asset_schema: Option<Box<Assetschema>>,
    #[serde(default)]
    pub initial_supply: Option<i64>,
    #[serde(default)]
    pub max_supply: Option<i64>,
    #[serde(default)]
    pub known_circulating_supply: Option<i64>,
    #[serde(default)]
    pub timestamp: Option<i64>,
    #[serde(default)]
    pub name: Option<String>,
    #[serde(default)]
    pub precision: Option<i64>,
    #[serde(default)]
    pub ticker: Option<String>,
    #[serde(default)]
    pub details: Option<String>,
    #[serde(default)]
    pub token: Option<Box<Token>>,
}

/// AssetNIA model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Assetnia {
    #[serde(default)]
    pub asset_id: Option<String>,
    #[serde(default)]
    pub ticker: Option<String>,
    #[serde(default)]
    pub name: Option<String>,
    #[serde(default)]
    pub details: Option<String>,
    #[serde(default)]
    pub precision: Option<i64>,
    #[serde(default)]
    pub issued_supply: Option<i64>,
    #[serde(default)]
    pub timestamp: Option<i64>,
    #[serde(default)]
    pub added_at: Option<i64>,
    #[serde(default)]
    pub balance: Option<Box<Assetbalanceresponse>>,
    #[serde(default)]
    pub media: Option<Box<Media>>,
}

/// AssetSchema enum.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum Assetschema {
    Nia,
    Uda,
    Cfa,
}

/// AssetUDA model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Assetuda {
    #[serde(default)]
    pub asset_id: Option<String>,
    #[serde(default)]
    pub ticker: Option<String>,
    #[serde(default)]
    pub name: Option<String>,
    #[serde(default)]
    pub details: Option<String>,
    #[serde(default)]
    pub precision: Option<i64>,
    #[serde(default)]
    pub timestamp: Option<i64>,
    #[serde(default)]
    pub added_at: Option<i64>,
    #[serde(default)]
    pub balance: Option<Box<Assetbalanceresponse>>,
    #[serde(default)]
    pub token: Option<Box<Tokenlight>>,
}

/// AssignmentAny model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Assignmentany {
    #[serde(rename = "type")]
    pub r#type: String,
}

/// AssignmentFungible model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Assignmentfungible {
    #[serde(rename = "type")]
    pub r#type: String,
    pub value: i64,
}

/// AssignmentInflationRight model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Assignmentinflationright {
    #[serde(rename = "type")]
    pub r#type: String,
    pub value: i64,
}

/// AssignmentNonFungible model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Assignmentnonfungible {
    #[serde(rename = "type")]
    pub r#type: String,
}

/// AssignmentReplaceRight model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Assignmentreplaceright {
    #[serde(rename = "type")]
    pub r#type: String,
}

/// BackupRequest model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Backuprequest {
    #[serde(default)]
    pub backup_path: Option<String>,
    #[serde(default)]
    pub password: Option<String>,
}

/// BitcoinNetwork enum.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum Bitcoinnetwork {
    Mainnet,
    Testnet,
    Testnet4,
    Signet,
    Regtest,
}

/// BlockTime model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Blocktime {
    #[serde(default)]
    pub height: Option<i64>,
    #[serde(default)]
    pub timestamp: Option<i64>,
}

/// BtcBalance model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Btcbalance {
    #[serde(default)]
    pub settled: Option<i64>,
    #[serde(default)]
    pub future: Option<i64>,
    #[serde(default)]
    pub spendable: Option<i64>,
}

/// BtcBalanceRequest model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Btcbalancerequest {
    #[serde(default)]
    pub skip_sync: Option<bool>,
}

/// BtcBalanceResponse model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Btcbalanceresponse {
    #[serde(default)]
    pub vanilla: Option<Box<Btcbalance>>,
    #[serde(default)]
    pub colored: Option<Box<Btcbalance>>,
}

/// ChangePasswordRequest model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Changepasswordrequest {
    #[serde(default)]
    pub old_password: Option<String>,
    #[serde(default)]
    pub new_password: Option<String>,
}

/// Channel model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Channel {
    #[serde(default)]
    pub channel_id: Option<String>,
    #[serde(default)]
    pub funding_txid: Option<String>,
    #[serde(default)]
    pub peer_pubkey: Option<String>,
    #[serde(default)]
    pub peer_alias: Option<String>,
    #[serde(default)]
    pub short_channel_id: Option<i64>,
    #[serde(default)]
    pub status: Option<Box<Channelstatus>>,
    #[serde(default)]
    pub ready: Option<bool>,
    #[serde(default)]
    pub capacity_sat: Option<i64>,
    #[serde(default)]
    pub local_balance_sat: Option<i64>,
    #[serde(default)]
    pub outbound_balance_msat: Option<i64>,
    #[serde(default)]
    pub inbound_balance_msat: Option<i64>,
    #[serde(default)]
    pub next_outbound_htlc_limit_msat: Option<i64>,
    #[serde(default)]
    pub next_outbound_htlc_minimum_msat: Option<i64>,
    #[serde(default)]
    pub is_usable: Option<bool>,
    #[serde(default)]
    pub public: Option<bool>,
    #[serde(default)]
    pub asset_id: Option<String>,
    #[serde(default)]
    pub asset_local_amount: Option<i64>,
    #[serde(default)]
    pub asset_remote_amount: Option<i64>,
}

/// ChannelStatus enum.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum Channelstatus {
    Opening,
    Opened,
    Closing,
}

/// CheckIndexerUrlRequest model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Checkindexerurlrequest {
    #[serde(default)]
    pub indexer_url: Option<String>,
}

/// CheckIndexerUrlResponse model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Checkindexerurlresponse {
    #[serde(default)]
    pub indexer_protocol: Option<Box<Indexerprotocol>>,
}

/// CheckProxyEndpointRequest model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Checkproxyendpointrequest {
    #[serde(default)]
    pub proxy_url: Option<String>,
}

/// CloseChannelRequest model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Closechannelrequest {
    #[serde(default)]
    pub channel_id: Option<String>,
    #[serde(default)]
    pub peer_pubkey: Option<String>,
    #[serde(default)]
    pub force: Option<bool>,
}

/// ConnectPeerRequest model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Connectpeerrequest {
    #[serde(default)]
    pub peer_pubkey_and_addr: Option<String>,
}

/// CreateUtxosRequest model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Createutxosrequest {
    #[serde(default)]
    pub up_to: Option<bool>,
    #[serde(default)]
    pub num: Option<i64>,
    #[serde(default)]
    pub size: Option<i64>,
    #[serde(default)]
    pub fee_rate: Option<f64>,
    #[serde(default)]
    pub skip_sync: Option<bool>,
}

/// DecodeLNInvoiceRequest model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Decodelninvoicerequest {
    #[serde(default)]
    pub invoice: Option<String>,
}

/// DecodeLNInvoiceResponse model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Decodelninvoiceresponse {
    #[serde(default)]
    pub amt_msat: Option<i64>,
    #[serde(default)]
    pub expiry_sec: Option<i64>,
    #[serde(default)]
    pub timestamp: Option<i64>,
    #[serde(default)]
    pub asset_id: Option<String>,
    #[serde(default)]
    pub asset_amount: Option<i64>,
    #[serde(default)]
    pub payment_hash: Option<String>,
    #[serde(default)]
    pub payment_secret: Option<String>,
    #[serde(default)]
    pub payee_pubkey: Option<String>,
    #[serde(default)]
    pub network: Option<Box<Bitcoinnetwork>>,
}

/// DecodeRGBInvoiceRequest model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Decodergbinvoicerequest {
    #[serde(default)]
    pub invoice: Option<String>,
}

/// DecodeRGBInvoiceResponse model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Decodergbinvoiceresponse {
    #[serde(default)]
    pub recipient_id: Option<String>,
    #[serde(default)]
    pub recipient_type: Option<Box<Recipienttype>>,
    #[serde(default)]
    pub asset_schema: Option<Box<Assetschema>>,
    #[serde(default)]
    pub asset_id: Option<String>,
    #[serde(default)]
    pub assignment: Option<Box<Assignment>>,
    #[serde(default)]
    pub network: Option<Box<Bitcoinnetwork>>,
    #[serde(default)]
    pub expiration_timestamp: Option<i64>,
    #[serde(default)]
    pub transport_endpoints: Option<Vec<String>>,
}

/// DisconnectPeerRequest model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Disconnectpeerrequest {
    #[serde(default)]
    pub peer_pubkey: Option<String>,
}

/// EmbeddedMedia model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Embeddedmedia {
    #[serde(default)]
    pub mime: Option<String>,
    #[serde(default)]
    pub data: Option<Vec<i64>>,
}

/// EmptyResponse model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Emptyresponse {
}

/// EstimateFeeRequest model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Estimatefeerequest {
    #[serde(default)]
    pub blocks: Option<i64>,
}

/// EstimateFeeResponse model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Estimatefeeresponse {
    #[serde(default)]
    pub fee_rate: Option<f64>,
}

/// FailTransfersRequest model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Failtransfersrequest {
    #[serde(default)]
    pub batch_transfer_idx: Option<i64>,
    #[serde(default)]
    pub no_asset_only: Option<bool>,
    #[serde(default)]
    pub skip_sync: Option<bool>,
}

/// FailTransfersResponse model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Failtransfersresponse {
    #[serde(default)]
    pub transfers_changed: Option<bool>,
}

/// GetAssetMediaRequest model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Getassetmediarequest {
    #[serde(default)]
    pub digest: Option<String>,
}

/// GetAssetMediaResponse model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Getassetmediaresponse {
    #[serde(default)]
    pub bytes_hex: Option<String>,
}

/// GetChannelIdRequest model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Getchannelidrequest {
    #[serde(default)]
    pub temporary_channel_id: Option<String>,
}

/// GetChannelIdResponse model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Getchannelidresponse {
    #[serde(default)]
    pub channel_id: Option<String>,
}

/// GetPaymentRequest model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Getpaymentrequest {
    #[serde(default)]
    pub payment_hash: Option<String>,
}

/// GetPaymentResponse model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Getpaymentresponse {
    #[serde(default)]
    pub payment: Option<Box<Payment>>,
}

/// GetSwapRequest model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Getswaprequest {
    #[serde(default)]
    pub payment_hash: Option<String>,
    #[serde(default)]
    pub taker: Option<bool>,
}

/// GetSwapResponse model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Getswapresponse {
    #[serde(default)]
    pub swap: Option<Box<Swap>>,
}

/// HTLCStatus enum.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum Htlcstatus {
    Pending,
    Succeeded,
    Failed,
}

/// IndexerProtocol enum.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum Indexerprotocol {
    Electrum,
    Esplora,
}

/// InitRequest model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Initrequest {
    #[serde(default)]
    pub password: Option<String>,
}

/// InitResponse model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Initresponse {
    #[serde(default)]
    pub mnemonic: Option<String>,
}

/// InvoiceStatus enum.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum Invoicestatus {
    Pending,
    Succeeded,
    Failed,
    Expired,
}

/// InvoiceStatusRequest model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Invoicestatusrequest {
    #[serde(default)]
    pub invoice: Option<String>,
}

/// InvoiceStatusResponse model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Invoicestatusresponse {
    #[serde(default)]
    pub status: Option<Box<Invoicestatus>>,
}

/// IssueAssetCFARequest model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Issueassetcfarequest {
    #[serde(default)]
    pub amounts: Option<Vec<i64>>,
    #[serde(default)]
    pub name: Option<String>,
    #[serde(default)]
    pub details: Option<String>,
    #[serde(default)]
    pub precision: Option<i64>,
    #[serde(default)]
    pub file_digest: Option<String>,
}

/// IssueAssetCFAResponse model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Issueassetcfaresponse {
    #[serde(default)]
    pub asset: Option<Box<Assetcfa>>,
}

/// IssueAssetNIARequest model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Issueassetniarequest {
    #[serde(default)]
    pub amounts: Option<Vec<i64>>,
    #[serde(default)]
    pub ticker: Option<String>,
    #[serde(default)]
    pub name: Option<String>,
    #[serde(default)]
    pub precision: Option<i64>,
}

/// IssueAssetNIAResponse model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Issueassetniaresponse {
    #[serde(default)]
    pub asset: Option<Box<Assetnia>>,
}

/// IssueAssetUDARequest model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Issueassetudarequest {
    #[serde(default)]
    pub ticker: Option<String>,
    #[serde(default)]
    pub name: Option<String>,
    #[serde(default)]
    pub details: Option<String>,
    #[serde(default)]
    pub precision: Option<i64>,
    #[serde(default)]
    pub media_file_digest: Option<String>,
    #[serde(default)]
    pub attachments_file_digests: Option<Vec<String>>,
}

/// IssueAssetUDAResponse model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Issueassetudaresponse {
    #[serde(default)]
    pub asset: Option<Box<Assetuda>>,
}

/// KeysendRequest model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Keysendrequest {
    #[serde(default)]
    pub dest_pubkey: Option<String>,
    #[serde(default)]
    pub amt_msat: Option<i64>,
    #[serde(default)]
    pub asset_id: Option<String>,
    #[serde(default)]
    pub asset_amount: Option<i64>,
}

/// KeysendResponse model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Keysendresponse {
    #[serde(default)]
    pub payment_hash: Option<String>,
    #[serde(default)]
    pub payment_preimage: Option<String>,
    #[serde(default)]
    pub status: Option<Box<Htlcstatus>>,
}

/// LNInvoiceRequest model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Lninvoicerequest {
    #[serde(default)]
    pub amt_msat: Option<i64>,
    #[serde(default)]
    pub expiry_sec: Option<i64>,
    #[serde(default)]
    pub asset_id: Option<String>,
    #[serde(default)]
    pub asset_amount: Option<i64>,
}

/// LNInvoiceResponse model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Lninvoiceresponse {
    #[serde(default)]
    pub invoice: Option<String>,
}

/// ListAssetsRequest model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Listassetsrequest {
    #[serde(default)]
    pub filter_asset_schemas: Option<Vec<Assetschema>>,
}

/// ListAssetsResponse model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Listassetsresponse {
    #[serde(default)]
    pub nia: Option<Vec<Assetnia>>,
    #[serde(default)]
    pub uda: Option<Vec<Assetuda>>,
    #[serde(default)]
    pub cfa: Option<Vec<Assetcfa>>,
}

/// ListChannelsResponse model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Listchannelsresponse {
    #[serde(default)]
    pub channels: Option<Vec<Channel>>,
}

/// ListPaymentsResponse model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Listpaymentsresponse {
    #[serde(default)]
    pub payments: Option<Vec<Payment>>,
}

/// ListPeersResponse model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Listpeersresponse {
    #[serde(default)]
    pub peers: Option<Vec<Peer>>,
}

/// ListSwapsResponse model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Listswapsresponse {
    #[serde(default)]
    pub maker: Option<Vec<Swap>>,
    #[serde(default)]
    pub taker: Option<Vec<Swap>>,
}

/// ListTransactionsRequest model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Listtransactionsrequest {
    #[serde(default)]
    pub skip_sync: Option<bool>,
}

/// ListTransactionsResponse model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Listtransactionsresponse {
    #[serde(default)]
    pub transactions: Option<Vec<Transaction>>,
}

/// ListTransfersRequest model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Listtransfersrequest {
    #[serde(default)]
    pub asset_id: Option<String>,
}

/// ListTransfersResponse model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Listtransfersresponse {
    #[serde(default)]
    pub transfers: Option<Vec<Transfer>>,
}

/// ListUnspentsRequest model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Listunspentsrequest {
    #[serde(default)]
    pub skip_sync: Option<bool>,
}

/// ListUnspentsResponse model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Listunspentsresponse {
    #[serde(default)]
    pub unspents: Option<Vec<Unspent>>,
}

/// MakerExecuteRequest model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Makerexecuterequest {
    #[serde(default)]
    pub swapstring: Option<String>,
    #[serde(default)]
    pub payment_secret: Option<String>,
    #[serde(default)]
    pub taker_pubkey: Option<String>,
}

/// MakerInitRequest model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Makerinitrequest {
    #[serde(default)]
    pub qty_from: Option<i64>,
    #[serde(default)]
    pub qty_to: Option<i64>,
    #[serde(default)]
    pub from_asset: Option<String>,
    #[serde(default)]
    pub to_asset: Option<String>,
    #[serde(default)]
    pub timeout_sec: Option<i64>,
}

/// MakerInitResponse model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Makerinitresponse {
    #[serde(default)]
    pub payment_hash: Option<String>,
    #[serde(default)]
    pub payment_secret: Option<String>,
    #[serde(default)]
    pub swapstring: Option<String>,
}

/// Media model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Media {
    #[serde(default)]
    pub file_path: Option<String>,
    #[serde(default)]
    pub mime: Option<String>,
}

/// NetworkInfoResponse model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Networkinforesponse {
    #[serde(default)]
    pub network: Option<Box<Bitcoinnetwork>>,
    #[serde(default)]
    pub height: Option<i64>,
}

/// NodeInfoResponse model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Nodeinforesponse {
    #[serde(default)]
    pub pubkey: Option<String>,
    #[serde(default)]
    pub num_channels: Option<i64>,
    #[serde(default)]
    pub num_usable_channels: Option<i64>,
    #[serde(default)]
    pub local_balance_sat: Option<i64>,
    #[serde(default)]
    pub eventual_close_fees_sat: Option<i64>,
    #[serde(default)]
    pub pending_outbound_payments_sat: Option<i64>,
    #[serde(default)]
    pub num_peers: Option<i64>,
    #[serde(default)]
    pub account_xpub_vanilla: Option<String>,
    #[serde(default)]
    pub account_xpub_colored: Option<String>,
    #[serde(default)]
    pub max_media_upload_size_mb: Option<i64>,
    #[serde(default)]
    pub rgb_htlc_min_msat: Option<i64>,
    #[serde(default)]
    pub rgb_channel_capacity_min_sat: Option<i64>,
    #[serde(default)]
    pub channel_capacity_min_sat: Option<i64>,
    #[serde(default)]
    pub channel_capacity_max_sat: Option<i64>,
    #[serde(default)]
    pub channel_asset_min_amount: Option<i64>,
    #[serde(default)]
    pub channel_asset_max_amount: Option<i64>,
    #[serde(default)]
    pub network_nodes: Option<i64>,
    #[serde(default)]
    pub network_channels: Option<i64>,
}

/// OpenChannelRequest model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Openchannelrequest {
    #[serde(default)]
    pub peer_pubkey_and_opt_addr: Option<String>,
    #[serde(default)]
    pub capacity_sat: Option<i64>,
    #[serde(default)]
    pub push_msat: Option<i64>,
    #[serde(default)]
    pub asset_amount: Option<i64>,
    #[serde(default)]
    pub asset_id: Option<String>,
    #[serde(default)]
    pub public: Option<bool>,
    #[serde(default)]
    pub with_anchors: Option<bool>,
    #[serde(default)]
    pub fee_base_msat: Option<i64>,
    #[serde(default)]
    pub fee_proportional_millionths: Option<i64>,
    #[serde(default)]
    pub temporary_channel_id: Option<String>,
}

/// OpenChannelResponse model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Openchannelresponse {
    #[serde(default)]
    pub temporary_channel_id: Option<String>,
}

/// Payment model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Payment {
    #[serde(default)]
    pub amt_msat: Option<i64>,
    #[serde(default)]
    pub asset_amount: Option<i64>,
    #[serde(default)]
    pub asset_id: Option<String>,
    #[serde(default)]
    pub payment_hash: Option<String>,
    #[serde(default)]
    pub inbound: Option<bool>,
    #[serde(default)]
    pub status: Option<Box<Htlcstatus>>,
    #[serde(default)]
    pub created_at: Option<i64>,
    #[serde(default)]
    pub updated_at: Option<i64>,
    #[serde(default)]
    pub payee_pubkey: Option<String>,
}

/// Peer model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Peer {
    #[serde(default)]
    pub pubkey: Option<String>,
}

/// PostAssetMediaRequest model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Postassetmediarequest {
    #[serde(default)]
    pub file: Option<String>,
}

/// PostAssetMediaResponse model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Postassetmediaresponse {
    #[serde(default)]
    pub digest: Option<String>,
}

/// ProofOfReserves model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Proofofreserves {
    #[serde(default)]
    pub utxo: Option<String>,
    #[serde(default)]
    pub proof: Option<Vec<i64>>,
}

/// RecipientType enum.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum Recipienttype {
    Blind,
    Witness,
}

/// RefreshRequest model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Refreshrequest {
    #[serde(default)]
    pub skip_sync: Option<bool>,
}

/// RestoreRequest model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Restorerequest {
    #[serde(default)]
    pub backup_path: Option<String>,
    #[serde(default)]
    pub password: Option<String>,
}

/// RevokeTokenRequest model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Revoketokenrequest {
    #[serde(default)]
    pub token: Option<String>,
}

/// RgbAllocation model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Rgballocation {
    #[serde(default)]
    pub asset_id: Option<String>,
    #[serde(default)]
    pub assignment: Option<Box<Assignmentfungible>>,
    #[serde(default)]
    pub settled: Option<bool>,
}

/// RgbInvoiceRequest model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Rgbinvoicerequest {
    #[serde(default)]
    pub min_confirmations: Option<i64>,
    #[serde(default)]
    pub asset_id: Option<String>,
    #[serde(default)]
    pub assignment: Option<Box<Assignment>>,
    #[serde(default)]
    pub duration_seconds: Option<i64>,
    #[serde(default)]
    pub witness: Option<bool>,
}

/// RgbInvoiceResponse model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Rgbinvoiceresponse {
    #[serde(default)]
    pub recipient_id: Option<String>,
    #[serde(default)]
    pub invoice: Option<String>,
    #[serde(default)]
    pub expiration_timestamp: Option<i64>,
    #[serde(default)]
    pub batch_transfer_idx: Option<i64>,
}

/// SendAssetRequest model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Sendassetrequest {
    #[serde(default)]
    pub asset_id: Option<String>,
    #[serde(default)]
    pub assignment: Option<Box<Assignmentfungible>>,
    #[serde(default)]
    pub recipient_id: Option<String>,
    #[serde(default)]
    pub witness_data: Option<Box<Witnessdata>>,
    #[serde(default)]
    pub donation: Option<bool>,
    #[serde(default)]
    pub fee_rate: Option<f64>,
    #[serde(default)]
    pub min_confirmations: Option<i64>,
    #[serde(default)]
    pub transport_endpoints: Option<Vec<String>>,
    #[serde(default)]
    pub skip_sync: Option<bool>,
}

/// SendAssetResponse model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Sendassetresponse {
    #[serde(default)]
    pub txid: Option<String>,
}

/// SendBtcRequest model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Sendbtcrequest {
    #[serde(default)]
    pub amount: Option<i64>,
    #[serde(default)]
    pub address: Option<String>,
    #[serde(default)]
    pub fee_rate: Option<f64>,
    #[serde(default)]
    pub skip_sync: Option<bool>,
}

/// SendBtcResponse model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Sendbtcresponse {
    #[serde(default)]
    pub txid: Option<String>,
}

/// SendOnionMessageRequest model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Sendonionmessagerequest {
    #[serde(default)]
    pub node_ids: Option<Vec<String>>,
    #[serde(default)]
    pub tlv_type: Option<i64>,
    #[serde(default)]
    pub data: Option<String>,
}

/// SendPaymentRequest model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Sendpaymentrequest {
    #[serde(default)]
    pub invoice: Option<String>,
}

/// SendPaymentResponse model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Sendpaymentresponse {
    #[serde(default)]
    pub payment_hash: Option<String>,
    #[serde(default)]
    pub payment_secret: Option<String>,
    #[serde(default)]
    pub status: Option<Box<Htlcstatus>>,
}

/// SignMessageRequest model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Signmessagerequest {
    #[serde(default)]
    pub message: Option<String>,
}

/// SignMessageResponse model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Signmessageresponse {
    #[serde(default)]
    pub signed_message: Option<String>,
}

/// Swap model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Swap {
    #[serde(default)]
    pub qty_from: Option<i64>,
    #[serde(default)]
    pub qty_to: Option<i64>,
    #[serde(default)]
    pub from_asset: Option<String>,
    #[serde(default)]
    pub to_asset: Option<String>,
    #[serde(default)]
    pub payment_hash: Option<String>,
    #[serde(default)]
    pub status: Option<Box<Swapstatus>>,
    #[serde(default)]
    pub requested_at: Option<i64>,
    #[serde(default)]
    pub initiated_at: Option<i64>,
    #[serde(default)]
    pub expires_at: Option<i64>,
    #[serde(default)]
    pub completed_at: Option<i64>,
}

/// SwapStatus enum.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum Swapstatus {
    Waiting,
    Pending,
    Succeeded,
    Expired,
    Failed,
}

/// TakerRequest model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Takerrequest {
    #[serde(default)]
    pub swapstring: Option<String>,
}

/// Token model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Token {
    #[serde(default)]
    pub index: Option<i64>,
    #[serde(default)]
    pub ticker: Option<String>,
    #[serde(default)]
    pub name: Option<String>,
    #[serde(default)]
    pub details: Option<String>,
    #[serde(default)]
    pub embedded_media: Option<Box<Embeddedmedia>>,
    #[serde(default)]
    pub media: Option<Box<Media>>,
    #[serde(default)]
    pub attachments: Option<std::collections::HashMap<String, Media>>,
    #[serde(default)]
    pub reserves: Option<Box<Proofofreserves>>,
}

/// TokenLight model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Tokenlight {
    #[serde(default)]
    pub index: Option<i64>,
    #[serde(default)]
    pub ticker: Option<String>,
    #[serde(default)]
    pub name: Option<String>,
    #[serde(default)]
    pub details: Option<String>,
    #[serde(default)]
    pub embedded_media: Option<bool>,
    #[serde(default)]
    pub media: Option<Box<Media>>,
    #[serde(default)]
    pub attachments: Option<std::collections::HashMap<String, Media>>,
    #[serde(default)]
    pub reserves: Option<bool>,
}

/// Transaction model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Transaction {
    #[serde(default)]
    pub transaction_type: Option<Box<Transactiontype>>,
    #[serde(default)]
    pub txid: Option<String>,
    #[serde(default)]
    pub received: Option<i64>,
    #[serde(default)]
    pub sent: Option<i64>,
    #[serde(default)]
    pub fee: Option<i64>,
    #[serde(default)]
    pub confirmation_time: Option<Box<Blocktime>>,
}

/// TransactionType enum.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum Transactiontype {
    #[serde(rename = "RgbSend")]
    Rgbsend,
    Drain,
    #[serde(rename = "CreateUtxos")]
    Createutxos,
    User,
}

/// Transfer model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Transfer {
    #[serde(default)]
    pub idx: Option<i64>,
    #[serde(default)]
    pub created_at: Option<i64>,
    #[serde(default)]
    pub updated_at: Option<i64>,
    #[serde(default)]
    pub status: Option<Box<Transferstatus>>,
    #[serde(default)]
    pub requested_assignment: Option<Box<Assignmentfungible>>,
    #[serde(default)]
    pub assignments: Option<Vec<Assignmentfungible>>,
    #[serde(default)]
    pub kind: Option<Box<Transferkind>>,
    #[serde(default)]
    pub txid: Option<String>,
    #[serde(default)]
    pub recipient_id: Option<String>,
    #[serde(default)]
    pub receive_utxo: Option<String>,
    #[serde(default)]
    pub change_utxo: Option<String>,
    #[serde(default)]
    pub expiration: Option<i64>,
    #[serde(default)]
    pub transport_endpoints: Option<Vec<Transfertransportendpoint>>,
}

/// TransferKind enum.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum Transferkind {
    Issuance,
    #[serde(rename = "ReceiveBlind")]
    Receiveblind,
    #[serde(rename = "ReceiveWitness")]
    Receivewitness,
    Send,
    Inflation,
}

/// TransferStatus enum.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum Transferstatus {
    #[serde(rename = "WaitingCounterparty")]
    Waitingcounterparty,
    #[serde(rename = "WaitingConfirmations")]
    Waitingconfirmations,
    Settled,
    Failed,
}

/// TransferTransportEndpoint model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Transfertransportendpoint {
    #[serde(default)]
    pub endpoint: Option<String>,
    #[serde(default)]
    pub transport_type: Option<Box<Transporttype>>,
    #[serde(default)]
    pub used: Option<bool>,
}

/// TransportType enum.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum Transporttype {
    #[serde(rename = "JsonRpc")]
    Jsonrpc,
}

/// UnlockRequest model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Unlockrequest {
    #[serde(default)]
    pub password: Option<String>,
    #[serde(default)]
    pub bitcoind_rpc_username: Option<String>,
    #[serde(default)]
    pub bitcoind_rpc_password: Option<String>,
    #[serde(default)]
    pub bitcoind_rpc_host: Option<String>,
    #[serde(default)]
    pub bitcoind_rpc_port: Option<i64>,
    #[serde(default)]
    pub indexer_url: Option<String>,
    #[serde(default)]
    pub proxy_endpoint: Option<String>,
    #[serde(default)]
    pub announce_addresses: Option<Vec<String>>,
    #[serde(default)]
    pub announce_alias: Option<String>,
}

/// Unspent model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Unspent {
    #[serde(default)]
    pub utxo: Option<Box<Utxo>>,
    #[serde(default)]
    pub rgb_allocations: Option<Vec<Rgballocation>>,
}

/// Utxo model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Utxo {
    #[serde(default)]
    pub outpoint: Option<String>,
    #[serde(default)]
    pub btc_amount: Option<i64>,
    #[serde(default)]
    pub colorable: Option<bool>,
}

/// WitnessData model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Witnessdata {
    #[serde(default)]
    pub amount_sat: Option<f64>,
    #[serde(default)]
    pub blinding: Option<f64>,
}
