"""
Kaleidoswap SDK - Python

Pure Python SDK for interacting with the Kaleidoswap protocol.
Trade RGB assets on Lightning Network with ease.

Example:
    ```python
    from kaleidoswap_sdk import KaleidoClient

    async def main():
        client = KaleidoClient.create(
            base_url="https://api.kaleidoswap.com"
        )

        assets = await client.maker.list_assets()
        quote = await client.maker.get_quote(...)
    ```
"""

from .client import (
    KaleidoClient,
    get_sdk_name,
    get_version,
    to_display_units,
    to_smallest_units,
)
from .errors import (
    APIError,
    ConfigError,
    InsufficientBalanceError,
    KaleidoError,
    NetworkError,
    NodeNotConfiguredError,
    NotFoundError,
    QuoteExpiredError,
    RateLimitError,
    SwapError,
    TimeoutError,
    ValidationError,
    WebSocketError,
    map_http_error,
)
from .http_client import HttpClient
from .maker_client import MakerClient, SwapCompletionOptions
from .rln_client import RlnClient
from .types import (
    # Node Types - BTC
    AddressResponse,
    # API Types - Assets & Pairs
    Asset,
    AssetBalanceRequest,
    AssetBalanceResponse,
    # Node Types - RGB Assets
    AssetCFA,
    AssetDeliveryStatus,
    AssetMetadataRequest,
    AssetMetadataResponse,
    AssetNIA,
    # Enums (Node)
    AssetSchema,
    AssetsResponse,
    AssetUDA,
    BackupRequest,
    BitcoinNetwork,
    BtcBalance,
    BtcBalanceRequest,
    BtcBalanceResponse,
    ChangePasswordRequest,
    # Node Types - Channels
    Channel,
    ChannelDetails,
    ChannelFees,
    ChannelOrderResponse,
    ChannelStatus,
    CheckIndexerUrlRequest,
    CheckIndexerUrlResponse,
    CheckProxyEndpointRequest,
    CloseChannelRequest,
    ConfirmSwapRequest,
    ConfirmSwapResponse,
    ConnectPeerRequest,
    CreateOrderRequest,
    # API Types - Swap Orders
    CreateSwapOrderRequest,
    CreateSwapOrderResponse,
    CreateUtxosRequest,
    DecodeLNInvoiceRequest,
    DecodeLNInvoiceResponse,
    DecodeRGBInvoiceRequest,
    DecodeRGBInvoiceResponse,
    DisconnectPeerRequest,
    EmptyResponse,
    EstimateFeeRequest,
    EstimateFeeResponse,
    FailTransfersRequest,
    FailTransfersResponse,
    # API Types - Quotes & Routes
    Fee,
    GetAssetMediaRequest,
    GetAssetMediaResponse,
    GetChannelIdRequest,
    GetChannelIdResponse,
    # API Types - LSP
    GetInfoResponseModel,
    GetOrderRequest,
    GetPaymentRequest,
    GetPaymentResponse,
    GetSwapRequest,
    GetSwapResponse,
    HTLCStatus,
    IndexerProtocol,
    # Node Types - Wallet
    InitRequest,
    InitResponse,
    InvoiceStatus,
    InvoiceStatusRequest,
    InvoiceStatusResponse,
    IssueAssetCFARequest,
    IssueAssetCFAResponse,
    IssueAssetNIARequest,
    IssueAssetNIAResponse,
    IssueAssetUDARequest,
    IssueAssetUDAResponse,
    # Config
    KaleidoConfig,
    KeysendRequest,
    KeysendResponse,
    # Enums (API)
    Layer,
    ListAssetsRequest,
    ListAssetsResponse,
    ListChannelsResponse,
    ListPaymentsResponse,
    ListPeersResponse,
    ListSwapsResponse,
    ListTransactionsRequest,
    ListTransactionsResponse,
    ListTransfersRequest,
    ListTransfersResponse,
    ListUnspentsRequest,
    ListUnspentsResponse,
    # Node Types - Invoices
    LNInvoiceRequest,
    LNInvoiceResponse,
    MakerExecuteRequest,
    MakerExecuteResponse,
    MakerInitRequest,
    MakerInitResponse,
    MultiHopRoute,
    NetworkInfoResponse,
    # Node Types - Other
    NodeInfoResponse,
    NodeNetworkInfoResponse,
    # Node Types - Swaps
    NodeSwap,
    OpenChannelRequest,
    OpenChannelResponse,
    OrderHistoryResponse,
    OrderHistorySummary,
    OrderState,
    OrderStatsResponse,
    PaginationMeta,
    PairQuoteRequest,
    PairQuoteResponse,
    # Node Types - Payments
    Payment,
    PaymentBolt11,
    PaymentDetails,
    PaymentOnchain,
    PaymentState,
    PaymentStatus,
    # Node Types - Peers
    Peer,
    RateDecisionRequest,
    RateDecisionResponse,
    ReachabilityCell,
    ReachabilityMatrixResponse,
    ReceiverAddress,
    ReceiverAddressFormat,
    Recipient,
    RefreshRequest,
    RestoreRequest,
    RetryDeliveryRequest,
    RetryDeliveryResponse,
    RetryDeliveryStatus,
    RevokeTokenRequest,
    RgbInvoiceRequest,
    RgbInvoiceResponse,
    RoutesRequest,
    RoutesResponse,
    RouteStep,
    SendBtcRequest,
    SendBtcResponse,
    SendOnionMessageRequest,
    SendPaymentRequest,
    SendPaymentResponse,
    SendRgbRequest,
    SendRgbResponse,
    SignMessageRequest,
    SignMessageResponse,
    Swap,
    SwapLeg,
    SwapLegInput,
    SwapNodeInfoResponse,
    SwapOrder,
    SwapOrderRateDecisionRequest,
    SwapOrderRateDecisionResponse,
    SwapOrderStatus,
    SwapOrderStatusRequest,
    SwapOrderStatusResponse,
    # API Types - Atomic Swaps
    SwapRequest,
    SwapResponse,
    SwapRoute,
    SwapStatus,
    SwapStatusRequest,
    SwapStatusResponse,
    TradableAsset,
    TradingLimits,
    TradingPair,
    TradingPairsResponse,
    Transaction,
    Transfer,
    TransferKind,
    TransferStatus,
    UnlockRequest,
    Unspent,
)
from .utils import (
    MappedAsset,
    OrderSizeLimits,
    PrecisionHandler,
    ValidationResult,
    create_precision_handler,
    to_display_amount,
    to_raw_amount,
)
from .ws_client import (
    ConnectionEstablishedData,
    WebSocketMessage,
    WebSocketResponse,
    WSAction,
    WSClient,
    WSClientConfig,
)
from .ws_client import (
    QuoteRequest as WSQuoteRequest,
)
from .ws_client import (
    QuoteResponse as WSQuoteResponse,
)

__version__ = "0.4.0"
__all__ = [
    # Main client
    "KaleidoClient",
    "MakerClient",
    "RlnClient",
    "HttpClient",
    # Utility functions
    "to_smallest_units",
    "to_display_units",
    "to_raw_amount",
    "to_display_amount",
    "get_version",
    "get_sdk_name",
    # Precision utilities
    "PrecisionHandler",
    "create_precision_handler",
    "MappedAsset",
    "ValidationResult",
    "OrderSizeLimits",
    "SwapCompletionOptions",
    # WebSocket
    "WSClient",
    "WSClientConfig",
    "WSAction",
    "WSQuoteResponse",
    "WSQuoteRequest",
    "WebSocketMessage",
    "WebSocketResponse",
    "ConnectionEstablishedData",
    # Config
    "KaleidoConfig",
    # Errors
    "KaleidoError",
    "APIError",
    "NetworkError",
    "ValidationError",
    "TimeoutError",
    "WebSocketError",
    "NotFoundError",
    "ConfigError",
    "SwapError",
    "NodeNotConfiguredError",
    "QuoteExpiredError",
    "InsufficientBalanceError",
    "RateLimitError",
    "map_http_error",
    # Enums (API)
    "Layer",
    "ReceiverAddressFormat",
    "BitcoinNetwork",
    "SwapOrderStatus",
    "OrderState",
    "PaymentState",
    "PaymentStatus",
    "AssetDeliveryStatus",
    "SwapStatus",
    "RetryDeliveryStatus",
    # Enums (Node)
    "AssetSchema",
    "ChannelStatus",
    "HTLCStatus",
    "InvoiceStatus",
    "TransferStatus",
    "TransferKind",
    "IndexerProtocol",
    # API Types - Assets & Pairs
    "Asset",
    "AssetsResponse",
    "TradingPair",
    "TradingPairsResponse",
    "TradableAsset",
    "TradingLimits",
    # API Types - Quotes & Routes
    "Fee",
    "SwapLeg",
    "SwapLegInput",
    "SwapRoute",
    "ReceiverAddress",
    "MultiHopRoute",
    "RouteStep",
    "PairQuoteRequest",
    "PairQuoteResponse",
    "RoutesRequest",
    "RoutesResponse",
    "ReachabilityCell",
    "ReachabilityMatrixResponse",
    # API Types - Swap Orders
    "CreateSwapOrderRequest",
    "CreateSwapOrderResponse",
    "SwapOrder",
    "SwapOrderStatusRequest",
    "SwapOrderStatusResponse",
    "SwapOrderRateDecisionRequest",
    "SwapOrderRateDecisionResponse",
    "OrderHistoryResponse",
    "OrderHistorySummary",
    "OrderStatsResponse",
    "PaginationMeta",
    # API Types - Atomic Swaps
    "SwapRequest",
    "SwapResponse",
    "ConfirmSwapRequest",
    "ConfirmSwapResponse",
    "SwapStatusRequest",
    "SwapStatusResponse",
    "Swap",
    "SwapNodeInfoResponse",
    # API Types - LSP
    "GetInfoResponseModel",
    "NetworkInfoResponse",
    "ChannelFees",
    "ChannelDetails",
    "PaymentDetails",
    "PaymentBolt11",
    "PaymentOnchain",
    "CreateOrderRequest",
    "ChannelOrderResponse",
    "GetOrderRequest",
    "RateDecisionRequest",
    "RateDecisionResponse",
    "RetryDeliveryRequest",
    "RetryDeliveryResponse",
    # Node Types - Wallet
    "InitRequest",
    "InitResponse",
    "UnlockRequest",
    "BackupRequest",
    "RestoreRequest",
    "ChangePasswordRequest",
    # Node Types - BTC
    "AddressResponse",
    "BtcBalance",
    "BtcBalanceRequest",
    "BtcBalanceResponse",
    "SendBtcRequest",
    "SendBtcResponse",
    "ListTransactionsRequest",
    "ListTransactionsResponse",
    "Transaction",
    "ListUnspentsRequest",
    "ListUnspentsResponse",
    "Unspent",
    "CreateUtxosRequest",
    "EstimateFeeRequest",
    "EstimateFeeResponse",
    # Node Types - RGB Assets
    "AssetCFA",
    "AssetNIA",
    "AssetUDA",
    "AssetBalanceRequest",
    "AssetBalanceResponse",
    "AssetMetadataRequest",
    "AssetMetadataResponse",
    "GetAssetMediaRequest",
    "GetAssetMediaResponse",
    "IssueAssetCFARequest",
    "IssueAssetCFAResponse",
    "IssueAssetNIARequest",
    "IssueAssetNIAResponse",
    "IssueAssetUDARequest",
    "IssueAssetUDAResponse",
    "ListAssetsRequest",
    "ListAssetsResponse",
    "Recipient",
    "SendRgbRequest",
    "SendRgbResponse",
    "ListTransfersRequest",
    "ListTransfersResponse",
    "Transfer",
    "RefreshRequest",
    "FailTransfersRequest",
    "FailTransfersResponse",
    # Node Types - Channels
    "Channel",
    "ListChannelsResponse",
    "OpenChannelRequest",
    "OpenChannelResponse",
    "CloseChannelRequest",
    "GetChannelIdRequest",
    "GetChannelIdResponse",
    # Node Types - Peers
    "Peer",
    "ListPeersResponse",
    "ConnectPeerRequest",
    "DisconnectPeerRequest",
    # Node Types - Invoices
    "LNInvoiceRequest",
    "LNInvoiceResponse",
    "RgbInvoiceRequest",
    "RgbInvoiceResponse",
    "DecodeLNInvoiceRequest",
    "DecodeLNInvoiceResponse",
    "DecodeRGBInvoiceRequest",
    "DecodeRGBInvoiceResponse",
    "InvoiceStatusRequest",
    "InvoiceStatusResponse",
    # Node Types - Payments
    "Payment",
    "ListPaymentsResponse",
    "SendPaymentRequest",
    "SendPaymentResponse",
    "KeysendRequest",
    "KeysendResponse",
    "GetPaymentRequest",
    "GetPaymentResponse",
    # Node Types - Swaps
    "NodeSwap",
    "ListSwapsResponse",
    "GetSwapRequest",
    "GetSwapResponse",
    "MakerInitRequest",
    "MakerInitResponse",
    "MakerExecuteRequest",
    "MakerExecuteResponse",
    # Node Types - Other
    "NodeInfoResponse",
    "NodeNetworkInfoResponse",
    "EmptyResponse",
    "SignMessageRequest",
    "SignMessageResponse",
    "SendOnionMessageRequest",
    "CheckIndexerUrlRequest",
    "CheckIndexerUrlResponse",
    "CheckProxyEndpointRequest",
    "RevokeTokenRequest",
]
