"""
Kaleidoswap SDK Type Definitions

Re-exports types from auto-generated OpenAPI models.
Run `make generate-python-sdk-models` to regenerate from OpenAPI specs.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import TYPE_CHECKING

# Re-export all generated API types (from maker.json OpenAPI spec)
from .generated.api_types import (
    Asset,
    AssetDeliveryStatus,
    AssetsResponse,
    BitcoinNetwork,
    ChannelDetails,
    ChannelFees,
    ChannelOrderResponse,
    ConfirmSwapRequest,
    ConfirmSwapResponse,
    CreateOrderRequest,
    CreateSwapOrderRequest,
    CreateSwapOrderResponse,
    Fee,
    GetInfoResponseModel,
    GetOrderRequest,
    Layer,
    MultiHopRoute,
    NetworkInfoResponse,
    OrderHistoryResponse,
    OrderHistorySummary,
    OrderState,
    OrderStatsResponse,
    PaginationMeta,
    PairQuoteRequest,
    PairQuoteResponse,
    PaymentBolt11,
    PaymentDetails,
    PaymentOnchain,
    PaymentState,
    PaymentStatus,
    RateDecisionRequest,
    RateDecisionResponse,
    ReachabilityCell,
    ReachabilityMatrixResponse,
    ReceiverAddress,
    ReceiverAddressFormat,
    RetryDeliveryRequest,
    RetryDeliveryResponse,
    RetryDeliveryStatus,
    RoutesRequest,
    RoutesResponse,
    RouteStep,
    Swap,
    SwapLeg,
    SwapLegInput,
    SwapNodeInfoResponse,
    SwapOrder,
    SwapOrderRateDecisionRequest,
    SwapOrderRateDecisionResponse,
    SwapOrderStatus,
    SwapOrderStatusRequest,
    SwapOrderStatusResponse,
    SwapRequest,
    SwapResponse,
    SwapRoute,
    SwapStatus,
    SwapStatusRequest,
    SwapStatusResponse,
    TradableAsset,
    TradingLimits,
    TradingPair,
    TradingPairsResponse,
)

# Re-export node types (from rln.yaml OpenAPI spec)
from .generated.node_types import (
    AddressResponse,
    AssetBalanceRequest,
    AssetBalanceResponse,
    AssetCFA,
    AssetMetadataRequest,
    AssetMetadataResponse,
    AssetNIA,
    AssetSchema,
    AssetUDA,
    BackupRequest,
    BtcBalance,
    BtcBalanceRequest,
    BtcBalanceResponse,
    ChangePasswordRequest,
    Channel,
    ChannelStatus,
    CheckIndexerUrlRequest,
    CheckIndexerUrlResponse,
    CheckProxyEndpointRequest,
    CloseChannelRequest,
    ConnectPeerRequest,
    CreateUtxosRequest,
    DecodeLNInvoiceRequest,
    DecodeLNInvoiceResponse,
    DecodeRGBInvoiceRequest,
    DecodeRGBInvoiceResponse,
    DisconnectPeerRequest,
    EmptyResponse,
    EstimateFeeRequest,
    EstimateFeeResponse,
    FailTransfersRequest,
    FailTransfersResponse,
    GetAssetMediaRequest,
    GetAssetMediaResponse,
    GetChannelIdRequest,
    GetChannelIdResponse,
    GetPaymentRequest,
    GetPaymentResponse,
    GetSwapRequest,
    GetSwapResponse,
    HTLCStatus,
    IndexerProtocol,
    InitRequest,
    InitResponse,
    InvoiceStatus,
    InvoiceStatusRequest,
    InvoiceStatusResponse,
    IssueAssetCFARequest,
    IssueAssetCFAResponse,
    IssueAssetNIARequest,
    IssueAssetNIAResponse,
    IssueAssetUDARequest,
    IssueAssetUDAResponse,
    KeysendRequest,
    KeysendResponse,
    ListAssetsRequest,
    ListAssetsResponse,
    ListChannelsResponse,
    ListPaymentsResponse,
    ListPeersResponse,
    ListSwapsResponse,
    ListTransactionsRequest,
    ListTransactionsResponse,
    ListTransfersRequest,
    ListTransfersResponse,
    ListUnspentsRequest,
    ListUnspentsResponse,
    LNInvoiceRequest,
    LNInvoiceResponse,
    MakerExecuteRequest,
    MakerExecuteResponse,
    MakerInitRequest,
    MakerInitResponse,
    NodeInfoResponse,
    OpenChannelRequest,
    OpenChannelResponse,
    Payment,
    Peer,
    Recipient,
    RefreshRequest,
    RestoreRequest,
    RevokeTokenRequest,
    RgbInvoiceRequest,
    RgbInvoiceResponse,
    SendBtcRequest,
    SendBtcResponse,
    SendOnionMessageRequest,
    SendPaymentRequest,
    SendPaymentResponse,
    SendRgbRequest,
    SendRgbResponse,
    SignMessageRequest,
    SignMessageResponse,
    Transaction,
    Transfer,
    TransferKind,
    TransferStatus,
    UnlockRequest,
    Unspent,
)

# Note: node_types also has Swap and NetworkInfoResponse but with different schemas
# Import them with prefix to avoid conflicts
from .generated.node_types import (
    NetworkInfoResponse as NodeNetworkInfoResponse,
)
from .generated.node_types import (
    Swap as NodeSwap,
)

if TYPE_CHECKING:
    pass


# =============================================================================
# SDK Configuration
# =============================================================================


@dataclass
class KaleidoConfig:
    """
    SDK client configuration.

    Attributes:
        base_url: Base URL for the Kaleidoswap API
        node_url: Optional URL for RGB Lightning Node
        api_key: Optional API key for authenticated requests
        timeout: Request timeout in seconds (default: 30)
        max_retries: Maximum retry attempts (default: 3)
        cache_ttl: Cache TTL in seconds (default: 60)
    """

    base_url: str
    node_url: str | None = None
    api_key: str | None = None
    timeout: float = 30.0
    max_retries: int = 3
    cache_ttl: int = 60


__all__ = [
    # Config
    "KaleidoConfig",
    # Enums (API)
    "Layer",
    "ReceiverAddressFormat",
    "BitcoinNetwork",
    "SwapOrderStatus",
    "OrderState",
    "PaymentState",
    "PaymentStatus",
    "AssetDeliveryStatus",
    "SwapStatus",
    "RetryDeliveryStatus",
    # Enums (Node)
    "AssetSchema",
    "ChannelStatus",
    "HTLCStatus",
    "InvoiceStatus",
    "TransferStatus",
    "TransferKind",
    "IndexerProtocol",
    # API Types - Assets & Pairs
    "Asset",
    "AssetsResponse",
    "TradingPair",
    "TradingPairsResponse",
    "TradableAsset",
    "TradingLimits",
    # API Types - Quotes & Routes
    "Fee",
    "SwapLeg",
    "SwapLegInput",
    "SwapRoute",
    "ReceiverAddress",
    "MultiHopRoute",
    "RouteStep",
    "PairQuoteRequest",
    "PairQuoteResponse",
    "RoutesRequest",
    "RoutesResponse",
    "ReachabilityCell",
    "ReachabilityMatrixResponse",
    # API Types - Swap Orders
    "CreateSwapOrderRequest",
    "CreateSwapOrderResponse",
    "SwapOrder",
    "SwapOrderStatusRequest",
    "SwapOrderStatusResponse",
    "SwapOrderRateDecisionRequest",
    "SwapOrderRateDecisionResponse",
    "OrderHistoryResponse",
    "OrderHistorySummary",
    "OrderStatsResponse",
    "PaginationMeta",
    # API Types - Atomic Swaps
    "SwapRequest",
    "SwapResponse",
    "ConfirmSwapRequest",
    "ConfirmSwapResponse",
    "SwapStatusRequest",
    "SwapStatusResponse",
    "Swap",
    "SwapNodeInfoResponse",
    # API Types - LSP
    "GetInfoResponseModel",
    "NetworkInfoResponse",
    "ChannelFees",
    "ChannelDetails",
    "PaymentDetails",
    "PaymentBolt11",
    "PaymentOnchain",
    "CreateOrderRequest",
    "ChannelOrderResponse",
    "GetOrderRequest",
    "RateDecisionRequest",
    "RateDecisionResponse",
    "RetryDeliveryRequest",
    "RetryDeliveryResponse",
    # Node Types - Wallet
    "InitRequest",
    "InitResponse",
    "UnlockRequest",
    "BackupRequest",
    "RestoreRequest",
    "ChangePasswordRequest",
    # Node Types - BTC
    "AddressResponse",
    "BtcBalance",
    "BtcBalanceRequest",
    "BtcBalanceResponse",
    "SendBtcRequest",
    "SendBtcResponse",
    "ListTransactionsRequest",
    "ListTransactionsResponse",
    "Transaction",
    "ListUnspentsRequest",
    "ListUnspentsResponse",
    "Unspent",
    "CreateUtxosRequest",
    "EstimateFeeRequest",
    "EstimateFeeResponse",
    # Node Types - RGB Assets
    "AssetCFA",
    "AssetNIA",
    "AssetUDA",
    "AssetBalanceRequest",
    "AssetBalanceResponse",
    "AssetMetadataRequest",
    "AssetMetadataResponse",
    "GetAssetMediaRequest",
    "GetAssetMediaResponse",
    "IssueAssetCFARequest",
    "IssueAssetCFAResponse",
    "IssueAssetNIARequest",
    "IssueAssetNIAResponse",
    "IssueAssetUDARequest",
    "IssueAssetUDAResponse",
    "ListAssetsRequest",
    "ListAssetsResponse",
    "Recipient",
    "SendRgbRequest",
    "SendRgbResponse",
    "ListTransfersRequest",
    "ListTransfersResponse",
    "Transfer",
    "RefreshRequest",
    "FailTransfersRequest",
    "FailTransfersResponse",
    # Node Types - Channels
    "Channel",
    "ListChannelsResponse",
    "OpenChannelRequest",
    "OpenChannelResponse",
    "CloseChannelRequest",
    "GetChannelIdRequest",
    "GetChannelIdResponse",
    # Node Types - Peers
    "Peer",
    "ListPeersResponse",
    "ConnectPeerRequest",
    "DisconnectPeerRequest",
    # Node Types - Invoices
    "LNInvoiceRequest",
    "LNInvoiceResponse",
    "RgbInvoiceRequest",
    "RgbInvoiceResponse",
    "DecodeLNInvoiceRequest",
    "DecodeLNInvoiceResponse",
    "DecodeRGBInvoiceRequest",
    "DecodeRGBInvoiceResponse",
    "InvoiceStatusRequest",
    "InvoiceStatusResponse",
    # Node Types - Payments
    "Payment",
    "ListPaymentsResponse",
    "SendPaymentRequest",
    "SendPaymentResponse",
    "KeysendRequest",
    "KeysendResponse",
    "GetPaymentRequest",
    "GetPaymentResponse",
    # Node Types - Swaps
    "NodeSwap",
    "ListSwapsResponse",
    "GetSwapRequest",
    "GetSwapResponse",
    "MakerInitRequest",
    "MakerInitResponse",
    "MakerExecuteRequest",
    "MakerExecuteResponse",
    # Node Types - Other
    "NodeInfoResponse",
    "NodeNetworkInfoResponse",
    "EmptyResponse",
    "SignMessageRequest",
    "SignMessageResponse",
    "SendOnionMessageRequest",
    "CheckIndexerUrlRequest",
    "CheckIndexerUrlResponse",
    "CheckProxyEndpointRequest",
    "RevokeTokenRequest",
]
