/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/lsps1/get_info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Info */
        get: operations["get_info_api_v1_lsps1_get_info_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/lsps1/network_info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Network Info
         * @description Get network information including current blockchain height and network type.
         */
        get: operations["get_network_info_api_v1_lsps1_network_info_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/lsps1/create_order": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Order */
        post: operations["create_order_api_v1_lsps1_create_order_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/lsps1/get_order": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Get Order */
        post: operations["get_order_api_v1_lsps1_get_order_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/swaps/nodeinfo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Node Info */
        get: operations["get_node_info_api_v1_swaps_nodeinfo_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/swaps/init": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Initiate Swap */
        post: operations["initiate_swap_api_v1_swaps_init_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/swaps/execute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm Swap */
        post: operations["confirm_swap_api_v1_swaps_execute_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/swaps/atomic/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Get Swap Status */
        post: operations["get_swap_status_api_v1_swaps_status_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/market/assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Assets */
        get: operations["list_assets_api_v1_market_assets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/market/pairs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Pairs */
        get: operations["get_pairs_api_v1_market_pairs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/market/quote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Get Quote */
        post: operations["get_quote_api_v1_market_quote_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AssetBalanceResponse */
        AssetBalanceResponse: {
            /**
             * Settled
             * @example 777
             */
            settled?: number | null;
            /**
             * Future
             * @example 777
             */
            future?: number | null;
            /**
             * Spendable
             * @example 777
             */
            spendable?: number | null;
            /**
             * Offchain Outbound
             * @example 444
             */
            offchain_outbound?: number | null;
            /**
             * Offchain Inbound
             * @example 0
             */
            offchain_inbound?: number | null;
        };
        /**
         * AssetIface
         * @enum {string}
         */
        AssetIface: "RGB20" | "RGB21" | "RGB25";
        /** AssetsOptions */
        AssetsOptions: {
            /**
             * Name
             * @default US Dollar Notes
             */
            name: string;
            /**
             * Asset Id
             * @default rgb:$i4cFKwt-2C5LZ3X-l$kOTGN-O6l1AOP-aP9COyn-7IeBkEM
             */
            asset_id: string | null;
            /**
             * Ticker
             * @default USDT
             */
            ticker: string;
            /**
             * Precision
             * @default 6
             */
            precision: number;
            /**
             * Issued Supply
             * @default 0
             */
            issued_supply: number;
            /**
             * Min Initial Client Amount
             * @default 0
             */
            min_initial_client_amount: number;
            /**
             * Max Initial Client Amount
             * @default 0
             */
            max_initial_client_amount: number;
            /**
             * Min Initial Lsp Amount
             * @default 0
             */
            min_initial_lsp_amount: number;
            /**
             * Max Initial Lsp Amount
             * @default 10000
             */
            max_initial_lsp_amount: number;
            /**
             * Min Channel Amount
             * @default 0
             */
            min_channel_amount: number;
            /**
             * Max Channel Amount
             * @default 10000
             */
            max_channel_amount: number;
        };
        /** AssetsResponse */
        AssetsResponse: {
            /** Assets */
            assets: components["schemas"]["ClientAsset"][];
            /**
             * Network
             * @default regtest
             */
            network: string;
            /** Timestamp */
            timestamp?: number | null;
        };
        /**
         * BitcoinNetwork
         * @enum {string}
         */
        BitcoinNetwork: "Mainnet" | "Testnet" | "Signet" | "Regtest";
        /** ChannelDetails */
        ChannelDetails: {
            /** Channel Id */
            channel_id?: string | null;
            /** Temporary Channel Id */
            temporary_channel_id?: string | null;
            /** Funded At */
            funded_at?: string | null;
            /** Funding Outpoint */
            funding_outpoint?: string | null;
            /** Expires At */
            expires_at?: string | null;
        };
        /** ClientAsset */
        ClientAsset: {
            /**
             * Asset Id
             * @example rgb:2dkSTbr-jFhznbPmo-TQafzswCN-av4gTsJjX-ttx6CNou5-M98k8Zd
             */
            asset_id?: string | null;
            asset_iface?: components["schemas"]["AssetIface"] | null;
            /**
             * Ticker
             * @example USDT
             */
            ticker?: string | null;
            /**
             * Name
             * @example Tether
             */
            name?: string | null;
            /**
             * Details
             * @example asset details
             */
            details?: string | null;
            /**
             * Precision
             * @example 0
             */
            precision?: number | null;
            /**
             * Issued Supply
             * @example 777
             */
            issued_supply?: number | null;
            /**
             * Timestamp
             * @example 1691160565
             */
            timestamp?: number | null;
            /**
             * Added At
             * @example 1691161979
             */
            added_at?: number | null;
            balance?: components["schemas"]["AssetBalanceResponse"] | null;
            media?: components["schemas"]["Media"] | null;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
        };
        /** ConfirmSwapRequest */
        ConfirmSwapRequest: {
            /**
             * Swapstring
             * @example 30/rgb:2dkSTbr-jFhznbPmo-TQafzswCN-av4gTsJjX-ttx6CNou5-M98k8Zd/10/rgb:2eVw8uw-8G88LQ2tQ-kexM12SoD-nCX8DmQrw-yLMu6JDfK-xx1SCfc/1715896416/9d342c6ba006e24abee84a2e034a22d5e30c1f2599fb9c3574d46d3cde3d65a2
             */
            swapstring: string;
            /**
             * Taker Pubkey
             * @example 034eedc97802d7e2766704bd06d6bfded8aa2d35a1a007e277fd7278f3dc962706
             */
            taker_pubkey: string;
            /**
             * Payment Hash
             * @example 9d342c6ba006e24abee84a2e034a22d5e30c1f2599fb9c3574d46d3cde3d65a2
             */
            payment_hash: string;
        };
        /** ConfirmSwapResponse */
        ConfirmSwapResponse: {
            /**
             * Status
             * @example 200
             */
            status: number;
            /**
             * Message
             * @example Swap executed successfully.
             */
            message: string;
        };
        /** CreateOrderRequest */
        CreateOrderRequest: {
            /** Client Pubkey */
            client_pubkey: string;
            /** Lsp Balance Sat */
            lsp_balance_sat: number;
            /** Client Balance Sat */
            client_balance_sat: number;
            /** Required Channel Confirmations */
            required_channel_confirmations: number;
            /** Funding Confirms Within Blocks */
            funding_confirms_within_blocks: number;
            /** Channel Expiry Blocks */
            channel_expiry_blocks: number;
            /** Token */
            token?: string | null;
            /** Refund Onchain Address */
            refund_onchain_address?: string | null;
            /**
             * Announce Channel
             * @default true
             */
            announce_channel: boolean;
            /** Asset Id */
            asset_id?: string | null;
            /** Lsp Asset Amount */
            lsp_asset_amount?: number | null;
            /** Client Asset Amount */
            client_asset_amount?: number | null;
        };
        /** GetInfoResponseModel */
        GetInfoResponseModel: {
            /** Lsp Connection Url */
            lsp_connection_url: string;
            options: components["schemas"]["OrderOptions"];
            /** Assets */
            assets: components["schemas"]["AssetsOptions"][];
        };
        /** GetOrderRequest */
        GetOrderRequest: {
            /** Order Id */
            order_id: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Media */
        Media: {
            /**
             * File Path
             * @example /path/to/media
             */
            file_path?: string | null;
            /**
             * Mime
             * @example text/plain
             */
            mime?: string | null;
        };
        /** NetworkInfoResponse */
        NetworkInfoResponse: {
            network?: components["schemas"]["BitcoinNetwork"] | null;
            /**
             * Height
             * @example 805434
             */
            height?: number | null;
        };
        /** NodeInfoResponse */
        NodeInfoResponse: {
            /**
             * Pubkey
             * @example 034eedc97802d7e2766704bd06d6bfded8aa2d35a1a007e277fd7278f3dc962706
             */
            pubkey: string | null;
            /**
             * Network
             * @example Signet
             */
            network: string | null;
            /**
             * Block Height
             * @example 805434
             */
            block_height: number | null;
        };
        /** OrderOptions */
        OrderOptions: {
            /**
             * Min Required Channel Confirmations
             * @default 0
             */
            min_required_channel_confirmations: number;
            /**
             * Min Funding Confirms Within Blocks
             * @default 0
             */
            min_funding_confirms_within_blocks: number;
            /** Min Onchain Payment Confirmations */
            min_onchain_payment_confirmations?: number | null;
            /**
             * Supports Zero Channel Reserve
             * @default true
             */
            supports_zero_channel_reserve: boolean;
            /** Min Onchain Payment Size Sat */
            min_onchain_payment_size_sat?: number | null;
            /**
             * Max Channel Expiry Blocks
             * @default 20160
             */
            max_channel_expiry_blocks: number;
            /**
             * Min Initial Client Balance Sat
             * @default 0
             */
            min_initial_client_balance_sat: number;
            /**
             * Max Initial Client Balance Sat
             * @default 1000000
             */
            max_initial_client_balance_sat: number;
            /**
             * Min Initial Lsp Balance Sat
             * @default 0
             */
            min_initial_lsp_balance_sat: number;
            /**
             * Max Initial Lsp Balance Sat
             * @default 16777215
             */
            max_initial_lsp_balance_sat: number;
            /**
             * Min Channel Balance Sat
             * @default 50000
             */
            min_channel_balance_sat: number;
            /**
             * Max Channel Balance Sat
             * @default 16777215
             */
            max_channel_balance_sat: number;
        };
        /** OrderResponse */
        OrderResponse: {
            /** Order Id */
            order_id: string;
            /** Client Pubkey */
            client_pubkey: string;
            /** Lsp Balance Sat */
            lsp_balance_sat: number;
            /** Client Balance Sat */
            client_balance_sat: number;
            /** Required Channel Confirmations */
            required_channel_confirmations: number;
            /** Funding Confirms Within Blocks */
            funding_confirms_within_blocks: number;
            /** Channel Expiry Blocks */
            channel_expiry_blocks: number;
            /**
             * Token
             * @default
             */
            token: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /** Announce Channel */
            announce_channel: boolean;
            order_state: components["schemas"]["OrderState"];
            payment: components["schemas"]["PaymentDetails"];
            channel?: components["schemas"]["ChannelDetails"] | null;
            /** Asset Id */
            asset_id?: string | null;
            /** Lsp Asset Amount */
            lsp_asset_amount?: number | null;
            /** Client Asset Amount */
            client_asset_amount?: number | null;
        };
        /**
         * OrderState
         * @enum {string}
         */
        OrderState: "CREATED" | "COMPLETED" | "FAILED";
        /** Pair */
        Pair: {
            /** Id */
            id?: string;
            /** Base Asset */
            base_asset: string;
            /** Base Asset Id */
            base_asset_id: string;
            /** Quote Asset */
            quote_asset: string;
            /** Quote Asset Id */
            quote_asset_id: string;
            /** Is Active */
            is_active: boolean;
            /** Min Base Order Size */
            min_base_order_size: number;
            /** Max Base Order Size */
            max_base_order_size: number;
            /** Min Quote Order Size */
            min_quote_order_size: number;
            /** Max Quote Order Size */
            max_quote_order_size: number;
            /** Base Precision */
            base_precision: number;
            /** Quote Precision */
            quote_precision: number;
            /** Quantity Precision */
            quantity_precision: number;
        };
        /** PairQuoteRequest */
        PairQuoteRequest: {
            /** Pair Id */
            pair_id: string;
            /** From Asset */
            from_asset: string;
            /** From Amount */
            from_amount: number;
            /** To Asset */
            to_asset: string;
        };
        /** PairQuoteResponse */
        PairQuoteResponse: {
            /** Rfq Id */
            rfq_id: string;
            /** Pair Id */
            pair_id: string;
            /** From Asset */
            from_asset: string;
            /** To Asset */
            to_asset: string;
            /** From Amount */
            from_amount: number;
            /** To Amount */
            to_amount: number;
            /** Price */
            price: number;
            /** Fee */
            fee: number;
            /** Fee Rate */
            fee_rate: number;
            /** Price Precision */
            price_precision: number;
            /** Timestamp */
            timestamp: number;
            /** Expires At */
            expires_at: number;
        };
        /** PairResponse */
        PairResponse: {
            /** Pairs */
            pairs: components["schemas"]["Pair"][];
        };
        /** PaymentBolt11 */
        PaymentBolt11: {
            state: components["schemas"]["PaymentState"];
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /** Fee Total Sat */
            fee_total_sat: number;
            /** Order Total Sat */
            order_total_sat: number;
            /** Invoice */
            invoice: string;
        };
        /** PaymentDetails */
        PaymentDetails: {
            bolt11: components["schemas"]["PaymentBolt11"];
            onchain: components["schemas"]["PaymentOnchain"];
        };
        /** PaymentOnchain */
        PaymentOnchain: {
            state: components["schemas"]["PaymentState"];
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /** Fee Total Sat */
            fee_total_sat: number;
            /** Order Total Sat */
            order_total_sat: number;
            /** Address */
            address: string;
            /** Min Fee For 0Conf */
            min_fee_for_0conf: number;
            /** Min Onchain Payment Confirmations */
            min_onchain_payment_confirmations: number;
            /** Refund Onchain Address */
            refund_onchain_address: string | null;
        };
        /**
         * PaymentState
         * @enum {string}
         */
        PaymentState: "EXPECT_PAYMENT" | "HOLD" | "PAID" | "REFUNDED";
        /** Swap */
        Swap: {
            /**
             * Qty From
             * @example 30
             */
            qty_from?: number | null;
            /**
             * Qty To
             * @example 10
             */
            qty_to?: number | null;
            /**
             * From Asset
             * @example rgb:2dkSTbr-jFhznbPmo-TQafzswCN-av4gTsJjX-ttx6CNou5-M98k8Zd
             */
            from_asset?: string | null;
            /**
             * To Asset
             * @example rgb:2eVw8uw-8G88LQ2tQ-kexM12SoD-nCX8DmQrw-yLMu6JDfK-xx1SCfc
             */
            to_asset?: string | null;
            /**
             * Payment Hash
             * @example 7c2c95b9c2aa0a7d140495b664de7973b76561de833f0dd84def3efa08941664
             */
            payment_hash?: string | null;
            status?: components["schemas"]["SwapStatus"] | null;
            /**
             * Requested At
             * @example 1691160765
             */
            requested_at?: number | null;
            /**
             * Initiated At
             * @example 1691168512
             */
            initiated_at?: number | null;
            /**
             * Expires At
             * @example 1691172703
             */
            expires_at?: number | null;
            /**
             * Completed At
             * @example 1691171075
             */
            completed_at?: number | null;
        };
        /** SwapRequest */
        SwapRequest: {
            /** Rfq Id */
            rfq_id: string;
            /** From Asset */
            from_asset: string;
            /** From Amount */
            from_amount: number;
            /** To Asset */
            to_asset: string;
            /** To Amount */
            to_amount: number;
        };
        /** SwapResponse */
        SwapResponse: {
            /**
             * Swapstring
             * @example 30/rgb:2dkSTbr-jFhznbPmo-TQafzswCN-av4gTsJjX-ttx6CNou5-M98k8Zd/10/rgb:2eVw8uw-8G88LQ2tQ-kexM12SoD-nCX8DmQrw-yLMu6JDfK-xx1SCfc/1715896416/9d342c6ba006e24abee84a2e034a22d5e30c1f2599fb9c3574d46d3cde3d65a2
             */
            swapstring: string;
            /**
             * Payment Hash
             * @example 9d342c6ba006e24abee84a2e034a22d5e30c1f2599fb9c3574d46d3cde3d65a2
             */
            payment_hash: string;
        };
        /**
         * SwapStatus
         * @enum {string}
         */
        SwapStatus: "Waiting" | "Pending" | "Succeeded" | "Expired" | "Failed";
        /** SwapStatusRequest */
        SwapStatusRequest: {
            /** Payment Hash */
            payment_hash: string;
        };
        /** SwapStatusResponse */
        SwapStatusResponse: {
            swap?: components["schemas"]["Swap"] | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_info_api_v1_lsps1_get_info_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetInfoResponseModel"];
                };
            };
        };
    };
    get_network_info_api_v1_lsps1_network_info_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NetworkInfoResponse"];
                };
            };
        };
    };
    create_order_api_v1_lsps1_create_order_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOrderRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_order_api_v1_lsps1_get_order_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GetOrderRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_node_info_api_v1_swaps_nodeinfo_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodeInfoResponse"];
                };
            };
        };
    };
    initiate_swap_api_v1_swaps_init_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SwapRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SwapResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_swap_api_v1_swaps_execute_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmSwapRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfirmSwapResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_swap_status_api_v1_swaps_status_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SwapStatusRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SwapStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_assets_api_v1_market_assets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetsResponse"];
                };
            };
        };
    };
    get_pairs_api_v1_market_pairs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PairResponse"];
                };
            };
        };
    };
    get_quote_api_v1_market_quote_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PairQuoteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PairQuoteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
