import { readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const packageJsonPath = resolve(repoRoot, 'typescript-sdk/package.json');
const versionPath = resolve(repoRoot, 'typescript-sdk/src/version.ts');
const sdkName = 'kaleido-sdk';

const packageJson = JSON.parse(await readFile(packageJsonPath, 'utf8'));
if (typeof packageJson.version !== 'string' || packageJson.version.length === 0) {
    throw new Error('typescript-sdk/package.json must define a non-empty version string');
}

const source = `// Generated by scripts/generate_typescript_version.mjs. Do not edit manually.

export const SDK_NAME = ${JSON.stringify(sdkName)};
export const SDK_VERSION = ${JSON.stringify(packageJson.version)};
`;

await writeFile(versionPath, source);
console.log(`Generated typescript-sdk/src/version.ts (${packageJson.version})`);
