"""Kaleidoswap SDK - Python SDK for interacting with Kaleidoswap and RGB Lightning nodes."""

from .client import KaleidoClient
from .http import HttpClient
from .websocket import WebSocketClient

# Re-export commonly used types from centralized models module
from .models import (
    # Kaleidoswap API models
    AssetsResponse,
    PairResponse,
    Pair,
    PairQuoteRequest,
    PairQuoteResponse,
    SwapRequest,
    SwapResponse,
    ConfirmSwapRequest,
    ConfirmSwapResponse,
    Swap,
    SwapStatus,
    SwapSettlement,
    GetInfoResponseModel,
    NetworkInfoResponse,
    NodeInfoResponse,
    CreateOrderRequest,
    OrderResponse,
    OrderState,
    PaymentState,
    CreateSwapOrderRequest,
    CreateSwapOrderResponse,
    SwapOrderStatus,
    SwapOrderStatusRequest,
    SwapOrderStatusResponse,
    ClientAsset,
    Fee,
    ChannelFees,
    # RGB Node models
    ListChannelsResponse,
    OpenChannelRequest,
    OpenChannelResponse,
    CloseChannelRequest,
    GetChannelIdRequest,
    GetChannelIdResponse,
    ListPeersResponse,
    ConnectPeerRequest,
    DisconnectPeerRequest,
    ListPaymentsResponse,
    GetPaymentRequest,
    GetPaymentResponse,
    SendPaymentRequest,
    SendPaymentResponse,
    KeysendRequest,
    KeysendResponse,
    LNInvoiceRequest,
    LNInvoiceResponse,
    DecodeLNInvoiceRequest,
    DecodeLNInvoiceResponse,
    InvoiceStatusRequest,
    InvoiceStatusResponse,
    AddressResponse,
    BtcBalanceRequest,
    BtcBalanceResponse,
    SendBtcRequest,
    SendBtcResponse,
    ListTransactionsRequest,
    ListTransactionsResponse,
    ListUnspentsRequest,
    ListUnspentsResponse,
    EstimateFeeRequest,
    EstimateFeeResponse,
    AssetBalanceRequest,
    AssetBalanceResponse,
    AssetMetadataRequest,
    AssetMetadataResponse,
    ListAssetsRequest,
    ListAssetsResponse,
    CreateUtxosRequest,
    ListTransfersRequest,
    ListTransfersResponse,
    FailTransfersRequest,
    FailTransfersResponse,
    RefreshRequest,
    RgbInvoiceRequest,
    RgbInvoiceResponse,
    DecodeRGBInvoiceRequest,
    DecodeRGBInvoiceResponse,
    SendAssetRequest,
    SendAssetResponse,
    IssueAssetNIARequest,
    IssueAssetNIAResponse,
    ListSwapsResponse,
    GetSwapRequest,
    GetSwapResponse,
    MakerInitRequest,
    MakerInitResponse,
    MakerExecuteRequest,
    TakerRequest,
    InitRequest,
    InitResponse,
    UnlockRequest,
    BackupRequest,
    RestoreRequest,
    ChangePasswordRequest,
    EmptyResponse,
    # Aliases
    Asset,
    TradingPair,
)

# Import retry utilities
from .retry import RetryConfig, with_retry

__version__ = "0.2.0"

__all__ = [
    # Client
    "KaleidoClient",
    "HttpClient",
    "WebSocketClient",
    # Version
    "__version__",
    # Generated Kaleidoswap API types
    "AssetsResponse",
    "PairResponse",
    "Pair",
    "PairQuoteRequest",
    "PairQuoteResponse",
    "SwapRequest",
    "SwapResponse",
    "ConfirmSwapRequest",
    "ConfirmSwapResponse",
    "Swap",
    "SwapStatus",
    "SwapSettlement",
    "GetInfoResponseModel",
    "NetworkInfoResponse",
    "NodeInfoResponse",
    "CreateOrderRequest",
    "OrderResponse",
    "OrderState",
    "PaymentState",
    "CreateSwapOrderRequest",
    "CreateSwapOrderResponse",
    "SwapOrderStatus",
    "SwapOrderStatusRequest",
    "SwapOrderStatusResponse",
    "ClientAsset",
    "Fee",
    "ChannelFees",
    # Generated RGB Node types
    "ListChannelsResponse",
    "OpenChannelRequest",
    "OpenChannelResponse",
    "CloseChannelRequest",
    "GetChannelIdRequest",
    "GetChannelIdResponse",
    "ListPeersResponse",
    "ConnectPeerRequest",
    "DisconnectPeerRequest",
    "ListPaymentsResponse",
    "GetPaymentRequest",
    "GetPaymentResponse",
    "SendPaymentRequest",
    "SendPaymentResponse",
    "KeysendRequest",
    "KeysendResponse",
    "LNInvoiceRequest",
    "LNInvoiceResponse",
    "DecodeLNInvoiceRequest",
    "DecodeLNInvoiceResponse",
    "InvoiceStatusRequest",
    "InvoiceStatusResponse",
    "AddressResponse",
    "BtcBalanceRequest",
    "BtcBalanceResponse",
    "SendBtcRequest",
    "SendBtcResponse",
    "ListTransactionsRequest",
    "ListTransactionsResponse",
    "ListUnspentsRequest",
    "ListUnspentsResponse",
    "EstimateFeeRequest",
    "EstimateFeeResponse",
    "AssetBalanceRequest",
    "AssetBalanceResponse",
    "AssetMetadataRequest",
    "AssetMetadataResponse",
    "ListAssetsRequest",
    "ListAssetsResponse",
    "CreateUtxosRequest",
    "ListTransfersRequest",
    "ListTransfersResponse",
    "FailTransfersRequest",
    "FailTransfersResponse",
    "RefreshRequest",
    "RgbInvoiceRequest",
    "RgbInvoiceResponse",
    "DecodeRGBInvoiceRequest",
    "DecodeRGBInvoiceResponse",
    "SendAssetRequest",
    "SendAssetResponse",
    "IssueAssetNIARequest",
    "IssueAssetNIAResponse",
    "ListSwapsResponse",
    "GetSwapRequest",
    "GetSwapResponse",
    "MakerInitRequest",
    "MakerInitResponse",
    "MakerExecuteRequest",
    "TakerRequest",
    "InitRequest",
    "InitResponse",
    "UnlockRequest",
    "BackupRequest",
    "RestoreRequest",
    "ChangePasswordRequest",
    "EmptyResponse",
    # Aliases
    "Asset",
    "TradingPair",
    # Retry utilities
    "RetryConfig",
    "with_retry",
]
