"""Models for the Kaleidoswap SDK.

This module centralizes all model imports from the generated API clients,
providing clean, easy-to-use model names throughout the SDK.
"""

# =============================================================================
# Kaleidoswap API Models
# =============================================================================

from .generated.kaleido.models import (
    AssetsResponse,
    PairResponse,
    Pair,
    PairQuoteRequest,
    PairQuoteResponse,
    SwapRequest,
    SwapResponse,
    ConfirmSwapRequest,
    ConfirmSwapResponse,
    Swap,
    SwapStatus,
    SwapStatusRequest,
    SwapStatusResponse,
    SwapSettlement,
    SwapOrder,
    SwapOrderSide,
    SwapOrderStatus,
    GetInfoResponseModel,
    NetworkInfoResponse,
    NodeInfoResponse,
    CreateOrderRequest,
    OrderResponse,
    GetOrderRequest,
    OrderState,
    OrderOptions,
    OrderHistoryResponse,
    OrderStatsResponse,
    OrderStatsResponseStatusCounts,
    PaymentState,
    PaymentStatus,
    PaymentDetails,
    PaymentBolt11,
    PaymentOnchain,
    CreateSwapOrderRequest,
    CreateSwapOrderResponse,
    SwapOrderStatusRequest,
    SwapOrderStatusResponse,
    ClientAsset,
    Fee,
    ChannelFees,
    ChannelDetails,
    RateDecisionRequest,
    RateDecisionResponse,
    RetryDeliveryRequest,
    RetryDeliveryResponse,
    RetryDeliveryStatus,
    SwapOrderRateDecisionRequest,
    SwapOrderRateDecisionResponse,
    AssetBalanceResponse,
    AssetDeliveryStatus,
    AssetIface,
    AssetsOptions,
    BitcoinNetwork,
    Media,
    HTTPValidationError,
    ValidationError,
)

# =============================================================================
# RGB Node API Models
# =============================================================================

from .generated.rgb_node.models import (
    # Swap/Trade related
    TakerRequest,
    MakerInitRequest,
    MakerInitResponse,
    MakerExecuteRequest,
    GetSwapRequest,
    GetSwapResponse,
    ListSwapsResponse,
    # Peer management
    ConnectPeerRequest,
    DisconnectPeerRequest,
    ListPeersResponse,
    Peer,
    # Payment/Invoice related
    GetPaymentRequest,
    GetPaymentResponse,
    ListPaymentsResponse,
    SendPaymentRequest,
    SendPaymentResponse,
    KeysendRequest,
    KeysendResponse,
    LNInvoiceRequest,
    LNInvoiceResponse,
    DecodeLNInvoiceRequest,
    DecodeLNInvoiceResponse,
    InvoiceStatus,
    InvoiceStatusRequest,
    InvoiceStatusResponse,
    RgbInvoiceRequest,
    RgbInvoiceResponse,
    DecodeRGBInvoiceRequest,
    DecodeRGBInvoiceResponse,
    Payment,
    # On-chain related
    AddressResponse,
    SendBtcRequest,
    SendBtcResponse,
    BtcBalance,
    BtcBalanceRequest,
    BtcBalanceResponse,
    CreateUtxosRequest,
    EstimateFeeRequest,
    EstimateFeeResponse,
    ListUnspentsRequest,
    ListUnspentsResponse,
    Unspent,
    Utxo,
    # Channel management
    OpenChannelRequest,
    OpenChannelResponse,
    CloseChannelRequest,
    GetChannelIdRequest,
    GetChannelIdResponse,
    ListChannelsResponse,
    Channel,
    ChannelStatus,
    HTLCStatus,
    # RGB Asset related
    AssetBalanceRequest,
    AssetMetadataRequest,
    AssetMetadataResponse,
    ListAssetsRequest,
    ListAssetsResponse,
    IssueAssetCFARequest,
    IssueAssetCFAResponse,
    IssueAssetNIARequest,
    IssueAssetNIAResponse,
    IssueAssetUDARequest,
    IssueAssetUDAResponse,
    SendAssetRequest,
    SendAssetResponse,
    AssetCFA,
    AssetNIA,
    AssetUDA,
    AssetSchema,
    RgbAllocation,
    # Transfer related
    ListTransfersRequest,
    ListTransfersResponse,
    FailTransfersRequest,
    FailTransfersResponse,
    Transfer,
    TransferKind,
    TransferStatus,
    TransferTransportEndpoint,
    # Transaction related
    ListTransactionsRequest,
    ListTransactionsResponse,
    Transaction,
    TransactionType,
    # Media/Attachments
    GetAssetMediaRequest,
    GetAssetMediaResponse,
    PostAssetMediaRequest,
    PostAssetMediaResponse,
    EmbeddedMedia,
    # Token related
    Token,
    TokenLight,
    TokenAttachments,
    TokenLightAttachments,
    # Assignment types (RGB protocol)
    AssignmentAny,
    AssignmentAnyType,
    AssignmentFungible,
    AssignmentFungibleType,
    AssignmentInflationRight,
    AssignmentInflationRightType,
    AssignmentNonFungible,
    AssignmentNonFungibleType,
    AssignmentReplaceRight,
    AssignmentReplaceRightType,
    # Node operations
    InitRequest,
    InitResponse,
    UnlockRequest,
    BackupRequest,
    RestoreRequest,
    ChangePasswordRequest,
    RevokeTokenRequest,
    RefreshRequest,
    SignMessageRequest,
    SignMessageResponse,
    SendOnionMessageRequest,
    # Network/Node info
    NetworkInfoResponse as RgbNetworkInfoResponse,
    NodeInfoResponse as RgbNodeInfoResponse,
    # Indexer/Proxy
    CheckIndexerUrlRequest,
    CheckIndexerUrlResponse,
    CheckProxyEndpointRequest,
    IndexerProtocol,
    TransportType,
    # Other types
    EmptyResponse,
    ProofOfReserves,
    BlockTime,
    RecipientType,
    WitnessData,
    BitcoinNetwork as RgbBitcoinNetwork,
    Media as RgbMedia,
    Swap as RgbSwap,
    SwapStatus as RgbSwapStatus,
)

# =============================================================================
# Aliases for backward compatibility and convenience
# =============================================================================

# Use clean names for commonly used models
Asset = ClientAsset
TradingPair = Pair

# Request/Response aliases for cleaner API (if needed for tests)
QuoteRequest = PairQuoteRequest
QuoteResponse = PairQuoteResponse
InitMakerSwapRequest = SwapRequest
InitMakerSwapResponse = SwapResponse
ExecuteMakerSwapRequest = ConfirmSwapRequest
ExecuteMakerSwapResponse = ConfirmSwapResponse
GetSwapStatusRequest = SwapStatusRequest
GetSwapStatusResponse = SwapStatusResponse
WhitelistTradeRequest = TakerRequest
GetAssetMetadataRequest = AssetMetadataRequest

# =============================================================================
# Exports
# =============================================================================

__all__ = [
    # Kaleidoswap API Models
    "AssetsResponse",
    "PairResponse",
    "Pair",
    "PairQuoteRequest",
    "PairQuoteResponse",
    "SwapRequest",
    "SwapResponse",
    "ConfirmSwapRequest",
    "ConfirmSwapResponse",
    "Swap",
    "SwapStatus",
    "SwapStatusRequest",
    "SwapStatusResponse",
    "SwapSettlement",
    "SwapOrder",
    "SwapOrderSide",
    "SwapOrderStatus",
    "GetInfoResponseModel",
    "NetworkInfoResponse",
    "NodeInfoResponse",
    "CreateOrderRequest",
    "OrderResponse",
    "GetOrderRequest",
    "OrderState",
    "OrderOptions",
    "OrderHistoryResponse",
    "OrderStatsResponse",
    "OrderStatsResponseStatusCounts",
    "PaymentState",
    "PaymentStatus",
    "PaymentDetails",
    "PaymentBolt11",
    "PaymentOnchain",
    "CreateSwapOrderRequest",
    "CreateSwapOrderResponse",
    "SwapOrderStatusRequest",
    "SwapOrderStatusResponse",
    "ClientAsset",
    "Fee",
    "ChannelFees",
    "ChannelDetails",
    "RateDecisionRequest",
    "RateDecisionResponse",
    "RetryDeliveryRequest",
    "RetryDeliveryResponse",
    "RetryDeliveryStatus",
    "SwapOrderRateDecisionRequest",
    "SwapOrderRateDecisionResponse",
    "AssetBalanceResponse",
    "AssetDeliveryStatus",
    "AssetIface",
    "AssetsOptions",
    "BitcoinNetwork",
    "Media",
    "HTTPValidationError",
    "ValidationError",
    # RGB Node Models
    "TakerRequest",
    "MakerInitRequest",
    "MakerInitResponse",
    "MakerExecuteRequest",
    "GetSwapRequest",
    "GetSwapResponse",
    "ListSwapsResponse",
    "ConnectPeerRequest",
    "DisconnectPeerRequest",
    "ListPeersResponse",
    "Peer",
    "GetPaymentRequest",
    "GetPaymentResponse",
    "ListPaymentsResponse",
    "SendPaymentRequest",
    "SendPaymentResponse",
    "KeysendRequest",
    "KeysendResponse",
    "LNInvoiceRequest",
    "LNInvoiceResponse",
    "DecodeLNInvoiceRequest",
    "DecodeLNInvoiceResponse",
    "InvoiceStatus",
    "InvoiceStatusRequest",
    "InvoiceStatusResponse",
    "RgbInvoiceRequest",
    "RgbInvoiceResponse",
    "DecodeRGBInvoiceRequest",
    "DecodeRGBInvoiceResponse",
    "Payment",
    "AddressResponse",
    "SendBtcRequest",
    "SendBtcResponse",
    "BtcBalance",
    "BtcBalanceRequest",
    "BtcBalanceResponse",
    "CreateUtxosRequest",
    "EstimateFeeRequest",
    "EstimateFeeResponse",
    "ListUnspentsRequest",
    "ListUnspentsResponse",
    "Unspent",
    "Utxo",
    "OpenChannelRequest",
    "OpenChannelResponse",
    "CloseChannelRequest",
    "GetChannelIdRequest",
    "GetChannelIdResponse",
    "ListChannelsResponse",
    "Channel",
    "ChannelStatus",
    "HTLCStatus",
    "AssetBalanceRequest",
    "AssetBalanceResponse",
    "AssetMetadataRequest",
    "AssetMetadataResponse",
    "ListAssetsRequest",
    "ListAssetsResponse",
    "IssueAssetCFARequest",
    "IssueAssetCFAResponse",
    "IssueAssetNIARequest",
    "IssueAssetNIAResponse",
    "IssueAssetUDARequest",
    "IssueAssetUDAResponse",
    "SendAssetRequest",
    "SendAssetResponse",
    "AssetCFA",
    "AssetNIA",
    "AssetUDA",
    "AssetSchema",
    "RgbAllocation",
    "ListTransfersRequest",
    "ListTransfersResponse",
    "FailTransfersRequest",
    "FailTransfersResponse",
    "Transfer",
    "TransferKind",
    "TransferStatus",
    "TransferTransportEndpoint",
    "ListTransactionsRequest",
    "ListTransactionsResponse",
    "Transaction",
    "TransactionType",
    "GetAssetMediaRequest",
    "GetAssetMediaResponse",
    "PostAssetMediaRequest",
    "PostAssetMediaResponse",
    "EmbeddedMedia",
    "Token",
    "TokenLight",
    "TokenAttachments",
    "TokenLightAttachments",
    "AssignmentAny",
    "AssignmentAnyType",
    "AssignmentFungible",
    "AssignmentFungibleType",
    "AssignmentInflationRight",
    "AssignmentInflationRightType",
    "AssignmentNonFungible",
    "AssignmentNonFungibleType",
    "AssignmentReplaceRight",
    "AssignmentReplaceRightType",
    "InitRequest",
    "InitResponse",
    "UnlockRequest",
    "BackupRequest",
    "RestoreRequest",
    "ChangePasswordRequest",
    "RevokeTokenRequest",
    "RefreshRequest",
    "SignMessageRequest",
    "SignMessageResponse",
    "SendOnionMessageRequest",
    "RgbNetworkInfoResponse",
    "RgbNodeInfoResponse",
    "CheckIndexerUrlRequest",
    "CheckIndexerUrlResponse",
    "CheckProxyEndpointRequest",
    "IndexerProtocol",
    "TransportType",
    "EmptyResponse",
    "ProofOfReserves",
    "BlockTime",
    "RecipientType",
    "WitnessData",
    "RgbBitcoinNetwork",
    "RgbMedia",
    "RgbSwap",
    "RgbSwapStatus",
    # Aliases
    "Asset",
    "TradingPair",
    "QuoteRequest",
    "QuoteResponse",
    "InitMakerSwapRequest",
    "InitMakerSwapResponse",
    "ExecuteMakerSwapRequest",
    "ExecuteMakerSwapResponse",
    "GetSwapStatusRequest",
    "GetSwapStatusResponse",
    "WhitelistTradeRequest",
    "GetAssetMetadataRequest",
]
